"""Short-lived informational health-consultation runtime adapter.

This adapter does not diagnose or prescribe.  It performs a conservative,
deterministic red-flag screen before an informational LLM response is
generated by the API layer.  Conversation state remains in memory and is
purged when the parent session closes.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


_EMERGENCY_SIGNALS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "breathing.severe_difficulty",
        ("숨을 못 쉬", "숨이 안 쉬", "호흡이 안", "질식", "can't breathe", "cannot breathe"),
    ),
    (
        "cardiac.chest_pain_high_risk",
        ("가슴을 짓누", "식은땀과 가슴", "흉통과 호흡", "chest pressure", "chest pain and sweating"),
    ),
    (
        "neurologic.stroke_like",
        ("한쪽 마비", "말이 어눌", "갑자기 말을 못", "얼굴 한쪽", "one-sided weakness", "slurred speech"),
    ),
    (
        "consciousness.altered",
        ("의식이 없", "깨우기 어렵", "갑자기 의식", "unconscious", "cannot wake"),
    ),
    (
        "bleeding.uncontrolled",
        ("피가 멈추지", "피를 토", "토혈", "uncontrolled bleeding", "vomiting blood"),
    ),
    (
        "allergy.airway",
        ("입술이 붓고 숨", "혀가 붓고 숨", "목이 붓고 숨", "anaphylaxis", "swollen tongue and breathing"),
    ),
    (
        "self_harm.immediate_risk",
        ("죽고 싶", "자살하려", "해칠 계획", "kill myself", "suicide plan"),
    ),
)

_URGENT_SIGNALS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("breathing.difficulty", ("숨이 차", "호흡곤란", "breathless", "short of breath")),
    ("chest.pain", ("가슴 통증", "흉통", "chest pain")),
    ("bleeding.possible", ("피가 나", "혈변", "검은변", "객혈", "blood in stool", "coughing blood")),
    ("pregnancy.warning", ("임신 중 출혈", "임신인데 피", "pregnant and bleeding")),
)


@dataclass
class HealthInformationSession:
    """Collect health questions and attach a conservative safety assessment."""

    session_id: str
    turn: int = 0
    history: list[dict[str, Any]] = field(default_factory=list)
    closed: bool = False

    def process(self, message: str) -> dict[str, Any]:
        if self.closed:
            raise RuntimeError("health information session is closed")
        query = message.strip()
        if not query:
            raise ValueError("health information query must not be empty")
        self.turn += 1
        safety = assess_health_information_safety(query)
        state = {
            "status": "active",
            "mode_id": "health_information",
            "runtime_adapter": "health_information_advisor",
            "turn": self.turn,
            "query": query,
            "safety_status": safety,
            "independent_diagnosis_or_treatment": False,
            "must_express_uncertainty": True,
            "response_storage": "memory_only",
        }
        self.history.append(state)
        return state

    def result(self) -> dict[str, Any]:
        latest = self.history[-1] if self.history else None
        return {
            "status": "informational_consultation",
            "turns": self.turn,
            "latest_safety_status": latest["safety_status"] if latest else None,
            "independent_diagnosis_or_treatment": False,
            "response_storage": "memory_only",
        }

    def close(self) -> dict[str, Any]:
        self.history.clear()
        self.closed = True
        return {"status": "closed", "response_state_purged": True}


def assess_health_information_safety(text: str) -> dict[str, Any]:
    normalized = text.casefold()
    emergency = [
        signal_id
        for signal_id, phrases in _EMERGENCY_SIGNALS
        if any(phrase in normalized for phrase in phrases)
    ]
    if emergency:
        return {
            "level": "emergency_suspected",
            "matched_signals": emergency,
            "action_ko": (
                "응급 위험 신호가 의심됩니다. 답변을 기다리거나 온라인 정보만으로 판단하지 말고 "
                "즉시 119 또는 가까운 응급실에 도움을 요청하세요."
            ),
            "diagnosis": None,
        }
    urgent = [
        signal_id
        for signal_id, phrases in _URGENT_SIGNALS
        if any(phrase in normalized for phrase in phrases)
    ]
    if urgent:
        return {
            "level": "urgent_assessment_suggested",
            "matched_signals": urgent,
            "action_ko": (
                "시간에 민감한 증상일 가능성을 배제할 수 없습니다. 증상이 심하거나 악화되면 119·응급실을 이용하고, "
                "그렇지 않더라도 가능한 한 빨리 의료진에게 평가받으세요."
            ),
            "diagnosis": None,
        }
    return {
        "level": "no_red_flag_detected_from_text",
        "matched_signals": [],
        "action_ko": (
            "입력한 문장만으로 뚜렷한 응급 위험 신호는 확인되지 않았지만, 이는 응급상황을 배제한다는 뜻이 아닙니다."
        ),
        "diagnosis": None,
    }
