#!/usr/bin/env python3
"""Materialize unreviewed paediatric growth and development knowledge."""
from profile_support import *

P, RFE = "pediatric-growth-development", "rfe.pediatric_growth_development"
M, SN = "mapping.snomed-mrcm.pediatric-growth-development", "http://snomed.info/sct"
ACQUIRED_AT = "2026-07-16T02:00:00Z"
SOURCES = ["source.aap.developmental-surveillance.2020", "source.cdc.act-early.2026", "source.nice.ng75.2017", "source.who.child-growth-standards", "source.stom.pediatric-growth.20260716"]
G = {k: f"group.pediatric.{k}" for k in ("routing", "safety", "growth", "development", "feeding", "context", "followup")}
C, S, D, R = ["intent.characterize_symptom"], ["intent.screen_red_flags"], ["intent.differentiate_common_causes"], ["intent.risk_assessment"]


def Q(fid, display, value_type, key, wording, score, groups, intents, **kwargs):
    return entry(P, fid, display, value_type, key, wording, score, key, groups, intents=intents, **kwargs)


def fragment():
    e = [
        Q("pediatric.primary_group", "Primary Growth or Development Concern", "coded", "primary-group", "이번 방문은 키·체중·머리둘레 성장, 전반적 발달, 말·언어, 운동, 사회성·행동, 학습·학교생활, 이미 진단·치료 중인 발달문제 추적 중 무엇에 가깝나요?", 200, [G["routing"]], C, allowed_values=["growth_trajectory", "global_development", "speech_language", "motor_coordination", "social_behavioral", "learning_school", "established_condition_followup", "other_unclear"]),
        Q("pediatric.acute_loss_of_skills_or_rapid_regression", "Acute Developmental Regression", "boolean", "acute-regression", "며칠~몇 주 사이에 이전에 하던 말·걷기·손 사용·사람 반응 같은 기술을 갑자기 잃거나 빠르게 나빠졌나요?", 199, [G["safety"], G["development"]], S, safety_relevant=True),
        Q("pediatric.current_seizure_reduced_consciousness_or_unresponsiveness", "Seizure or Reduced Consciousness", "boolean", "seizure-consciousness", "지금 경련, 깨우기 어려움, 의식 저하 또는 평소와 달리 반응하지 않는 상태가 있나요?", 198, [G["safety"]], S, safety_relevant=True),
        Q("pediatric.new_focal_weakness_ataxia_or_inability_to_walk", "Acute Neurologic Deficit", "boolean", "focal-neurologic", "새 한쪽 힘 빠짐·얼굴 처짐, 심한 비틀거림 또는 이전에 걷던 아이가 갑자기 걷지 못하나요?", 197, [G["safety"]], S, safety_relevant=True),
        Q("pediatric.breathing_choking_cyanosis_or_unsafe_swallow", "Breathing or Swallowing Compromise", "boolean", "airway-feeding", "먹거나 마실 때 숨을 못 쉬거나 반복 질식, 입술이 파래짐 또는 침도 삼키지 못하는 상태가 있나요?", 196, [G["safety"], G["feeding"]], S, safety_relevant=True),
        Q("pediatric.severe_dehydration_or_unable_to_take_fluids", "Severe Dehydration or Intake Failure", "boolean", "dehydration", "거의 마시지 못하고 소변이 현저히 줄었거나 입이 매우 마름·눈물 없음·축 처짐이 있나요?", 195, [G["safety"], G["feeding"]], S, safety_relevant=True),
        Q("pediatric.bulging_fontanelle_repeated_vomiting_or_head_warning", "Raised Intracranial Pressure Warning", "boolean", "head-warning", "영아의 대천문이 팽팽하게 불룩하거나 반복 구토·심한 두통·의식 변화와 함께 머리 크기나 상태가 급격히 달라졌나요?", 194, [G["safety"], G["growth"]], S, safety_relevant=True),
        Q("pediatric.infant_under_three_months_fever_or_seriously_unwell", "Young Infant Serious Illness", "boolean", "young-infant", "생후 3개월 미만이며 38°C 이상 발열 또는 수유 저하·축 처짐·호흡 이상으로 많이 아파 보이나요?", 193, [G["safety"]], S, safety_relevant=True),
        Q("pediatric.rapid_weight_loss_or_prolonged_near_zero_intake", "Severe Nutrition Warning", "boolean", "severe-nutrition", "빠른 체중 감소가 있거나 하루 이상 거의 먹고 마시지 못하면서 상태가 나빠지고 있나요?", 192, [G["safety"], G["growth"], G["feeding"]], S, safety_relevant=True),
        Q("pediatric.possible_poisoning_overdose_or_hypoglycemia", "Toxic or Metabolic Emergency", "boolean", "toxic-metabolic", "약·화학물질을 먹었을 가능성, 과량 투여 또는 저혈당 의심과 함께 발달·행동·의식이 갑자기 변했나요?", 191, [G["safety"], G["context"]], S, safety_relevant=True),
        Q("pediatric.safeguarding_injury_neglect_or_unsafe_environment", "Safeguarding Concern", "boolean", "safeguarding", "설명되지 않는 손상, 학대·방임 가능성, 돌봄 공백 또는 아이가 집에 돌아가면 안전하지 않을 우려가 있나요?", 190, [G["safety"], G["context"]], S, safety_relevant=True),
        Q("pediatric.immediate_self_harm_harm_to_others_or_extreme_behavioral_danger", "Immediate Behavioural Safety Risk", "boolean", "behavioral-danger", "아이·청소년이 지금 자신이나 다른 사람을 해칠 생각·행동이 있거나 보호자가 안전을 유지할 수 없나요?", 189, [G["safety"], G["development"]], S, safety_relevant=True),
        Q("pediatric.sudden_hearing_or_vision_loss", "Sudden Sensory Loss", "boolean", "sensory-loss", "갑자기 듣지 못하거나 보지 못하는 변화가 생겼나요?", 188, [G["safety"], G["development"]], S, safety_relevant=True),

        Q("pediatric.information_source_observers_and_reliability", "Information Sources and Observers", "string", "information-source", "누가 답변하며 부모·보호자, 아이 본인, 교사·보육자 중 누가 어떤 상황에서 관찰했나요? 서로 다른 의견도 알려주세요.", 178, [G["routing"]], C),
        Q("pediatric.chronological_age_birth_date_and_corrected_age", "Age and Corrected Age Context", "string", "age-context", "현재 만 나이와 개월 수, 미숙아라면 출생 주수와 교정연령을 알려주세요.", 177, [G["routing"], G["context"]], C),
        Q("pediatric.main_concern_onset_course_and_trigger", "Main Concern and Course", "string", "concern-course", "가장 걱정되는 변화가 무엇이며 언제 처음 알아차렸고 지속·호전·악화·변동하는지 알려주세요.", 176, [G["routing"]], C),
        Q("pediatric.skills_never_acquired_versus_lost", "Delayed versus Lost Skills", "string", "acquired-lost", "아직 배우지 못한 기술인지, 이전에 하다가 잃은 기술인지와 마지막으로 확실히 했던 시기를 알려주세요.", 175, [G["development"]], C, terminology_binding={"system": SN, "code": "248290002"}, mrcm_ref=M),
        Q("pediatric.variability_across_home_school_and_people", "Cross-setting Variability", "string", "setting-variability", "집·어린이집·학교와 익숙한 사람·낯선 사람 앞에서 능력이나 행동이 어떻게 다른가요?", 174, [G["development"]], C),

        Q("pediatric.birth_weight_length_and_head_circumference", "Birth Measurements", "string", "birth-measures", "출생 체중·키·머리둘레와 측정 기록의 출처를 알려주세요.", 170, [G["growth"], G["context"]], R),
        Q("pediatric.current_weight_date_method_and_clothing", "Current Weight", "string", "current-weight", "최근 체중, 측정 날짜·저울·옷이나 기저귀 상태를 알려주세요.", 169, [G["growth"]], C),
        Q("pediatric.current_length_or_height_date_and_method", "Current Length or Height", "string", "current-height", "최근 누운 키 또는 선 키, 측정 날짜와 방법을 알려주세요.", 168, [G["growth"]], C),
        Q("pediatric.current_head_circumference_date_and_method", "Current Head Circumference", "string", "head-circumference", "해당 연령이면 최근 머리둘레, 측정 날짜와 방법을 알려주세요.", 167, [G["growth"]], C),
        Q("pediatric.previous_growth_measurements_and_trajectory", "Growth Trajectory", "string", "growth-trajectory", "이전 체중·키·머리둘레의 날짜별 기록과 성장곡선 백분위 또는 z점수 변화가 있으면 알려주세요.", 166, [G["growth"]], R),
        Q("pediatric.weight_loss_or_centile_crossing_context", "Growth Change Concern", "string", "growth-change", "실제 체중 감소나 성장선 하락을 언제 지적받았고 당시 질병·식사 변화가 있었는지 알려주세요.", 165, [G["growth"]], R, terminology_binding={"system": SN, "code": "36440009"}, mrcm_ref=M),
        Q("pediatric.bmi_or_weight_for_length_if_recorded", "BMI or Weight-for-length", "string", "bmi", "의료기관에서 계산한 BMI 또는 키 대비 체중 지표와 날짜·사용 성장차트를 알려주세요.", 164, [G["growth"]], R),
        Q("pediatric.biological_parent_heights_and_puberty_timing", "Family Growth Context", "string", "parent-heights", "가능하면 생물학적 부모의 키와 가족의 성장·사춘기 시작 시기, 아이의 현재 사춘기 변화를 알려주세요.", 163, [G["growth"], G["context"]], R),
        Q("pediatric.growth_measurement_conflicts_and_source", "Growth Measurement Conflicts", "string", "measure-conflict", "가정·검진·병원 측정값이 다르다면 각각의 값·날짜·방법을 알려주세요.", 162, [G["growth"]], R),

        Q("pediatric.gross_motor_skills_and_mobility", "Gross Motor Development", "string", "gross-motor", "고개 가누기, 앉기, 서기, 걷기·달리기·계단·점프 등 현재 가능한 큰 운동과 어려운 동작을 알려주세요.", 158, [G["development"]], C),
        Q("pediatric.fine_motor_hand_use_and_laterality", "Fine Motor and Hand Use", "string", "fine-motor", "물건 잡기·옮기기, 손가락 사용, 그림·쓰기·도구 사용과 양손 차이 또는 뚜렷한 한쪽 손만 쓰는 시기를 알려주세요.", 157, [G["development"]], C),
        Q("pediatric.receptive_language_and_following_directions", "Receptive Language", "string", "receptive-language", "이름·말·지시를 얼마나 이해하고 한 단계 또는 여러 단계 지시를 어떻게 따르나요?", 156, [G["development"]], C),
        Q("pediatric.expressive_language_words_sentences_and_intelligibility", "Expressive Language", "string", "expressive-language", "소리·몸짓·단어·문장으로 무엇을 표현하며 가족과 낯선 사람이 말의 어느 정도를 알아듣나요?", 155, [G["development"]], C),
        Q("pediatric.social_attention_eye_contact_joint_attention_and_play", "Social Communication and Play", "string", "social-play", "눈맞춤, 이름 반응, 관심 공유·가리키기, 모방, 또래 놀이와 상상놀이 모습을 알려주세요.", 154, [G["development"]], C),
        Q("pediatric.cognitive_problem_solving_and_learning", "Cognitive and Learning Skills", "string", "cognitive", "물건 찾기·원인결과 이해·문제해결, 색·숫자·글자·기억·새 학습에서 가능한 것과 어려움을 알려주세요.", 153, [G["development"]], C),
        Q("pediatric.adaptive_self_care_and_daily_living", "Adaptive Daily Living", "string", "adaptive", "먹기·옷 입기·씻기·화장실·안전 인식·간단한 집안일에서 혼자 하는 정도를 알려주세요.", 152, [G["development"]], R),
        Q("pediatric.behavior_emotion_attention_and_regulation", "Behaviour and Emotional Regulation", "string", "behavior", "주의집중, 과잉활동, 불안·기분, 짜증·폭발, 변화 적응과 스스로 진정하는 모습을 알려주세요.", 151, [G["development"]], R),
        Q("pediatric.repetitive_behavior_sensory_preferences_and_rigidity", "Repetitive and Sensory Features", "string", "sensory-behavior", "반복 움직임·말·놀이, 강한 고집·일과 변화 어려움과 소리·빛·촉감·냄새·음식 감각 반응을 알려주세요.", 150, [G["development"]], R),
        Q("pediatric.hearing_screen_response_and_ear_history", "Hearing Context", "string", "hearing", "신생아·최근 청력검사 결과, 소리·이름 반응, 반복 중이염이나 보청기 사용을 알려주세요.", 149, [G["development"], G["context"]], R),
        Q("pediatric.vision_screen_alignment_and_visual_function", "Vision Context", "string", "vision", "시력검사, 사시·눈 떨림·물체 추적·가까이 보기와 안경 사용을 알려주세요.", 148, [G["development"], G["context"]], R),
        Q("pediatric.sleep_pattern_snoring_and_daytime_effect", "Sleep Context", "string", "sleep", "잠드는 시각·총 수면·야간 각성, 코골이·무호흡 의심과 낮 기능 영향을 알려주세요.", 147, [G["development"], G["context"]], R),
        Q("pediatric.toileting_bowel_bladder_and_regression", "Toileting and Elimination", "string", "toileting", "배변·배뇨 훈련 상태, 변비·실금·야뇨와 이미 익힌 배변기술이 퇴행했는지 알려주세요.", 146, [G["development"], G["feeding"]], R),

        Q("pediatric.feeding_method_schedule_and_amount", "Feeding Pattern", "string", "feeding-pattern", "모유·분유·이유식·일반식 종류, 횟수·양·식사 시간과 최근 변화를 알려주세요.", 140, [G["feeding"]], R),
        Q("pediatric.appetite_selectivity_texture_and_mealtime_behavior", "Appetite and Mealtime Behaviour", "string", "mealtime", "식욕, 음식 종류·질감 제한, 식사 거부·구토 유도와 식사 중 보호자-아이 상호작용을 알려주세요.", 139, [G["feeding"]], R),
        Q("pediatric.chewing_swallowing_coughing_and_feeding_fatigue", "Oral Motor and Swallowing", "string", "swallowing", "씹기·삼키기 어려움, 먹을 때 기침·사레·젖은 목소리, 숨참·쉽게 지침이 있나요?", 138, [G["feeding"]], R),
        Q("pediatric.vomiting_diarrhea_constipation_abdominal_or_stool_change", "Gastrointestinal Context", "string", "gi-context", "구토·설사·변비·복통, 혈변·기름진 변 등 대변 변화와 성장 문제의 관계를 알려주세요.", 137, [G["feeding"]], D),
        Q("pediatric.food_allergy_intolerance_and_dietary_restriction", "Dietary Restriction", "string", "diet-restriction", "음식 알레르기·불내성, 채식·제한식과 부족할 수 있는 식품군·보충제를 알려주세요.", 136, [G["feeding"]], R),
        Q("pediatric.feeding_diary_observation_and_support", "Feeding Observation and Support", "string", "feeding-support", "식사일지·영상·직접 관찰 결과와 영양·수유 상담 또는 치료 경험을 알려주세요.", 135, [G["feeding"], G["followup"]], R),

        Q("pediatric.pregnancy_exposures_infections_and_complications", "Pregnancy History", "string", "pregnancy-history", "임신 중 질환·감염·약물·음주·흡연·물질 노출과 태아 성장 문제를 알려주세요.", 130, [G["context"]], R),
        Q("pediatric.gestation_delivery_resuscitation_and_nicu", "Birth and Neonatal Course", "string", "birth-history", "재태주수, 분만 방법·합병증, 출생 직후 소생술·신생아중환자실 치료와 기간을 알려주세요.", 129, [G["context"]], R),
        Q("pediatric.newborn_metabolic_hearing_and_other_screen_results", "Newborn Screening", "string", "newborn-screen", "신생아 대사·청력 등 선별검사 결과와 재검·확진 여부를 알려주세요.", 128, [G["context"]], R),
        Q("pediatric.conditions_hospitalizations_surgeries_and_medicines", "Medical History and Medicines", "string", "medical-history", "진단받은 질환, 입원·수술·큰 감염·머리 손상과 현재 약·보충제 이름·용량을 알려주세요.", 127, [G["context"]], R),
        Q("pediatric.family_growth_development_learning_genetic_history", "Family Developmental History", "string", "family-history", "가족의 성장·말·학습·발달·자폐·주의력·신경근육·유전질환과 혈연관계를 알려주세요.", 126, [G["context"]], R),
        Q("pediatric.home_languages_communication_and_interpreter_needs", "Language and Communication Context", "string", "language-context", "집과 교육기관에서 쓰는 언어·수어, 아이가 각 언어에 노출된 시기와 통역·의사소통 지원 필요를 알려주세요.", 125, [G["context"]], R),
        Q("pediatric.household_caregivers_stability_and_social_needs", "Household and Social Context", "string", "social-context", "함께 사는 사람과 주 돌봄자, 최근 돌봄·주거 변화, 식품·교통·경제·양육 지원 필요를 알려주세요.", 124, [G["context"]], R),
        Q("pediatric.daycare_school_grade_attendance_and_teacher_concerns", "Education Context", "string", "education", "어린이집·학교·학년, 출석, 교사 우려, 학업·또래 관계와 필요한 지원을 알려주세요.", 123, [G["context"], G["followup"]], R),
        Q("pediatric.screen_time_physical_activity_and_play_opportunities", "Activity and Play Opportunities", "string", "activity", "하루 화면 사용, 신체활동·야외활동·책 읽기·대화·놀이 기회를 알려주세요.", 122, [G["context"]], R),

        Q("pediatric.standardized_developmental_screen_name_date_and_result", "Developmental Screening Record", "string", "developmental-screen", "발달 선별검사의 정확한 이름·시행일·연령·원점수 또는 결과·시행기관을 알려주세요. 선별검사는 진단이 아닙니다.", 115, [G["followup"]], R),
        Q("pediatric.autism_specific_screen_name_date_and_result", "Autism-specific Screening Record", "string", "autism-screen", "자폐 관련 선별검사를 받았다면 검사명·시행일·결과와 후속 평가 여부를 알려주세요.", 114, [G["followup"]], R),
        Q("pediatric.prior_specialist_assessment_tests_and_results", "Prior Specialist Assessment", "string", "specialist-assessment", "소아과·발달·신경·유전·재활·청각·안과 평가와 검사 날짜·주요 결과를 알려주세요.", 113, [G["followup"]], R),
        Q("pediatric.early_intervention_therapy_education_plan_and_response", "Intervention and Education Plan", "string", "intervention", "언어·작업·물리·행동치료, 조기중재·특수교육 계획의 빈도·목표·반응과 중단 이유를 알려주세요.", 112, [G["followup"]], R),
        Q("pediatric.functional_participation_strengths_and_interests", "Function, Strengths and Interests", "string", "strengths-function", "가정·학교·지역활동 참여에서 도움이 필요한 부분과 아이의 강점·관심·잘하는 것을 알려주세요.", 111, [G["followup"]], R),
        Q("pediatric.caregiver_goal_priority_and_other_detail", "Caregiver and Child Priority", "string", "other-detail", "질문에 없지만 의료진에게 꼭 전달할 내용과 아이·보호자가 이번 진료에서 가장 원하는 도움을 알려주세요.", 80, [G["routing"], G["followup"]], C),
    ]
    safety = [("acute-regression", "pediatric.acute_loss_of_skills_or_rapid_regression", "urgent"), ("seizure-consciousness", "pediatric.current_seizure_reduced_consciousness_or_unresponsiveness", "emergency"), ("focal-neurologic", "pediatric.new_focal_weakness_ataxia_or_inability_to_walk", "emergency"), ("airway-feeding", "pediatric.breathing_choking_cyanosis_or_unsafe_swallow", "emergency"), ("dehydration", "pediatric.severe_dehydration_or_unable_to_take_fluids", "emergency"), ("head-warning", "pediatric.bulging_fontanelle_repeated_vomiting_or_head_warning", "emergency"), ("young-infant", "pediatric.infant_under_three_months_fever_or_seriously_unwell", "emergency"), ("severe-nutrition", "pediatric.rapid_weight_loss_or_prolonged_near_zero_intake", "urgent"), ("toxic-metabolic", "pediatric.possible_poisoning_overdose_or_hypoglycemia", "emergency"), ("safeguarding", "pediatric.safeguarding_injury_neglect_or_unsafe_environment", "urgent"), ("behavioral-danger", "pediatric.immediate_self_harm_harm_to_others_or_extreme_behavioral_danger", "emergency"), ("sensory-loss", "pediatric.sudden_hearing_or_vision_loss", "urgent")]
    rules = [safety_rule(P, key, {"fact": fid, "equals": True}, level, 1000 if level == "emergency" else 990) for key, fid, level in safety]
    return {"id": "knowledge.generated.pediatric-growth-development", "version": VERSION, "status": "research_only", "usage_modes": ["research_test", "simulation"], "source_manifest": "source-manifest.primary-care-pediatric-growth-development-research", "default_refresh": default_refresh(), "extra_nodes": [{"id": v, "type": "ClinicalGroup", "display": v.split(".")[-1]} for v in G.values()], "group_hypothesis_edges": [], "safety_rules": rules, "entries": e, "provenance": provenance(SOURCES)}


def completion(f):
    p = completion_policy(prefix=P, fragment=f, presentation_fact="pediatric.primary_group", question_budget=85, source_refs=SOURCES)
    common = ["pediatric.information_source_observers_and_reliability", "pediatric.chronological_age_birth_date_and_corrected_age", "pediatric.main_concern_onset_course_and_trigger", "pediatric.skills_never_acquired_versus_lost", "pediatric.variability_across_home_school_and_people", "pediatric.birth_weight_length_and_head_circumference", "pediatric.current_weight_date_method_and_clothing", "pediatric.current_length_or_height_date_and_method", "pediatric.current_head_circumference_date_and_method", "pediatric.previous_growth_measurements_and_trajectory", "pediatric.growth_measurement_conflicts_and_source", "pediatric.gross_motor_skills_and_mobility", "pediatric.fine_motor_hand_use_and_laterality", "pediatric.receptive_language_and_following_directions", "pediatric.expressive_language_words_sentences_and_intelligibility", "pediatric.social_attention_eye_contact_joint_attention_and_play", "pediatric.cognitive_problem_solving_and_learning", "pediatric.adaptive_self_care_and_daily_living", "pediatric.behavior_emotion_attention_and_regulation", "pediatric.hearing_screen_response_and_ear_history", "pediatric.vision_screen_alignment_and_visual_function", "pediatric.sleep_pattern_snoring_and_daytime_effect", "pediatric.feeding_method_schedule_and_amount", "pediatric.appetite_selectivity_texture_and_mealtime_behavior", "pediatric.chewing_swallowing_coughing_and_feeding_fatigue", "pediatric.pregnancy_exposures_infections_and_complications", "pediatric.gestation_delivery_resuscitation_and_nicu", "pediatric.newborn_metabolic_hearing_and_other_screen_results", "pediatric.conditions_hospitalizations_surgeries_and_medicines", "pediatric.family_growth_development_learning_genetic_history", "pediatric.home_languages_communication_and_interpreter_needs", "pediatric.household_caregivers_stability_and_social_needs", "pediatric.daycare_school_grade_attendance_and_teacher_concerns", "pediatric.standardized_developmental_screen_name_date_and_result", "pediatric.prior_specialist_assessment_tests_and_results", "pediatric.early_intervention_therapy_education_plan_and_response", "pediatric.functional_participation_strengths_and_interests", "pediatric.caregiver_goal_priority_and_other_detail"]
    cases = {"growth_trajectory": ["pediatric.weight_loss_or_centile_crossing_context", "pediatric.bmi_or_weight_for_length_if_recorded", "pediatric.biological_parent_heights_and_puberty_timing", "pediatric.vomiting_diarrhea_constipation_abdominal_or_stool_change", "pediatric.food_allergy_intolerance_and_dietary_restriction", "pediatric.feeding_diary_observation_and_support"], "global_development": ["pediatric.repetitive_behavior_sensory_preferences_and_rigidity", "pediatric.toileting_bowel_bladder_and_regression", "pediatric.autism_specific_screen_name_date_and_result"], "speech_language": ["pediatric.repetitive_behavior_sensory_preferences_and_rigidity", "pediatric.autism_specific_screen_name_date_and_result"], "motor_coordination": ["pediatric.toileting_bowel_bladder_and_regression", "pediatric.screen_time_physical_activity_and_play_opportunities"], "social_behavioral": ["pediatric.repetitive_behavior_sensory_preferences_and_rigidity", "pediatric.toileting_bowel_bladder_and_regression", "pediatric.autism_specific_screen_name_date_and_result", "pediatric.screen_time_physical_activity_and_play_opportunities"], "learning_school": ["pediatric.toileting_bowel_bladder_and_regression", "pediatric.screen_time_physical_activity_and_play_opportunities"], "established_condition_followup": ["pediatric.repetitive_behavior_sensory_preferences_and_rigidity", "pediatric.toileting_bowel_bladder_and_regression", "pediatric.autism_specific_screen_name_date_and_result", "pediatric.screen_time_physical_activity_and_play_opportunities"], "other_unclear": ["pediatric.caregiver_goal_priority_and_other_detail"]}
    p["required_facts"]["routine"], p["conditional_required_facts"] = common, [{"selector_fact": "pediatric.primary_group", "cases": cases}]
    return p


def source_docs():
    defs = [
        ("source.aap.developmental-surveillance.2020", "AAP", "Promoting Optimal Development: Developmental Surveillance and Screening", "Pediatrics-145-1-e20193449", "https://publications.aap.org/pediatrics/article/145/1/e20193449/36971/", "clinical_guideline", ["Developmental surveillance includes eliciting parent concerns, developmental history, observation, risks and strengths, documentation and shared findings at health supervision visits.", "Standardized general developmental screening is recommended at 9, 18 and 30 months, with evaluation or referral when surveillance raises concern; this package records screening provenance and does not reproduce a licensed tool."]),
        ("source.cdc.act-early.2026", "CDC", "Learn the Signs. Act Early developmental monitoring", "updated-2026-05", "https://www.cdc.gov/act-early/", "public_health_guidance", ["Milestones span social-emotional, language-communication, cognitive and movement domains; missed or lost skills and caregiver concern should be shared promptly.", "CDC milestone checklists are monitoring aids and are not substitutes for standardized validated developmental screening."]),
        ("source.nice.ng75.2017", "NICE", "Faltering growth: recognition and management", "NG75", "https://www.nice.org.uk/guidance/ng75", "nice_guidance", ["Growth assessment uses dated weight and length or height plotted with previous measurements; BMI and parental height context may be relevant by age.", "Clinical, developmental and social assessment plus detailed feeding history and, when appropriate, feeding observation support evaluation without indiscriminate testing."]),
        ("source.who.child-growth-standards", "WHO", "WHO Child Growth Standards", "current-web-2026", "https://www.who.int/tools/child-growth-standards", "public_health_guidance", ["WHO standards provide length or height, weight, weight-for-length or height, BMI, head circumference and velocity references; the package preserves raw measurements and chart identity rather than assigning centiles itself."]),
        ("source.stom.pediatric-growth.20260716", "Infoclinic", "STOM paediatric growth and development terminology lookup", "SNOMEDCT-20260701", "https://stom.infoclinic.co", "terminology_server", ["FHIR lookup confirmed active developmental-delay, failure-to-thrive, failure-to-gain-weight and macrocephaly concepts.", "Terminology and MRCM do not diagnose delay, determine age norms or replace standardized screening."]),
    ]
    artifacts = [{"id": i, "kind": "terminology_mrcm_query_summary" if profile == "terminology_server" else "clinical_guidance_metadata", "publisher": pub, "title": title, "version": version, "url": url, "language": "en", "digest": "live_response_summary_not_raw_cache" if profile == "terminology_server" else "metadata_only_not_cached", "license_status": "restricted" if pub in {"AAP", "NICE", "Infoclinic"} else "unknown", "complete": False, "monitor_profile": profile, "last_monitored_at": "2026-07-16", "monitor_result": "current_official_source_confirmed", "assertions": assertions} for i, pub, title, version, url, profile, assertions in defs]
    research = {"id": "source-manifest.primary-care-pediatric-growth-development-research", "version": VERSION, "acquired_at": ACQUIRED_AT, "status": "research_only", "artifacts": artifacts, "provenance": provenance([x[0] for x in defs])}
    paths = [("source.repository.foundation", "repository_specification", "FOUNDATION.md", True), ("source.generated.pediatric", "generated_clinical_knowledge", "knowledge/generated/pediatrics/growth-development/pediatric-growth-development.json", True), ("source.mapping.pediatric", "terminology_mapping", "mappings/terminology/snomed-mrcm-pediatric-growth-development.json", False), ("source.external.pediatric", "external_source_manifest", "sources/manifests/primary-care-pediatric-growth-development-research.json", False), ("source.policy.pediatric", "runtime_policy", "policies/primary-care-pediatric-growth-development-completion.json", True)]
    primary = {"id": "source-manifest.primary-care-pediatric-growth-development", "version": VERSION, "acquired_at": ACQUIRED_AT, "artifacts": [{"id": i, "kind": kind, "publisher": "clinical-interview-platform", "version": VERSION, "language": "en", "path": path, "digest": "computed_at_build", "license_status": "allowed" if complete else "unknown", "complete": complete} for i, kind, path, complete in paths], "provenance": provenance(["FOUNDATION.md", "PROJECT_CONTEXT.md"])}
    return primary, research


def cases(f):
    out = {}
    for i, rule in enumerate(f["safety_rules"]):
        fid, level, key = rule["when"]["fact"], rule["then"]["safety_level"], rule["id"].split("safety.")[1]
        out[f"PED-{key.upper()}.json"] = {"id": f"PED-{key.upper()}", "simulation_language": "ko", "persona": {"age": max(1, i)}, "initial_statement": {"ko": "아이 성장이나 발달이 걱정됩니다."}, "hidden_state": {fid: {"value": True}}, "expected": {"expected_safety_level": level, "expected_safety_action": "human_handoff", "expected_stop_reason": f"{level}_escalation", "expected_triggered_rules_contains": [rule["id"]], "expected_max_turns": 40, "forbidden_assertions": ["diagnosis.autism", "diagnosis.developmental_delay", "diagnosis.failure_to_thrive"]}, "provenance": provenance(SOURCES)}
    policy, by_id = completion(f), {x["fact"]["id"]: x["fact"] for x in f["entries"]}
    def routine(branch):
        required = set(policy["required_facts"]["always"] + policy["required_facts"]["routine"] + policy["conditional_required_facts"][0]["cases"][branch]); values = {}
        for fid in required:
            fact = by_id[fid]; values[fid] = {"value": False if fact["value_type"] == "boolean" else fact.get("allowed_values", ["없음"])[0] if fact["value_type"] == "coded" else "없음"}
        values["pediatric.primary_group"] = {"value": branch}; return values
    growth = routine("growth_trajectory"); growth["pediatric.current_weight_date_method_and_clothing"] = {"value": "오늘 병원 저울, 가벼운 옷 착용 13.2kg"}; growth["pediatric.growth_measurement_conflicts_and_source"] = {"value": "가정 13.8kg, 병원 13.2kg로 기기와 옷 차이 가능"}
    out["PED-GROWTH-MEASUREMENT-CONFLICT-ROUTINE.json"] = {"id": "PED-GROWTH-MEASUREMENT-CONFLICT-ROUTINE", "simulation_language": "ko", "persona": {"age": 3}, "initial_statement": {"ko": "아이 체중 증가가 느린 것 같아요."}, "hidden_state": growth, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_known_facts": {"pediatric.growth_measurement_conflicts_and_source": "가정 13.8kg, 병원 13.2kg로 기기와 옷 차이 가능"}, "expected_max_turns": 90, "forbidden_assertions": ["diagnosis.failure_to_thrive", "growth.percentile"]}, "provenance": provenance(SOURCES)}
    absent = routine("speech_language"); absent.pop("pediatric.birth_weight_length_and_head_circumference"); absent.pop("pediatric.information_source_observers_and_reliability")
    out["PED-LANGUAGE-DATA-ABSENT.json"] = {"id": "PED-LANGUAGE-DATA-ABSENT", "simulation_language": "ko", "persona": {"age": 2}, "initial_statement": {"ko": "말이 늦는 것 같지만 출생 기록은 없어요."}, "hidden_state": absent, "response_behavior": {"pediatric.birth_weight_length_and_head_circumference": {"dataAbsentReason": "asked-unknown"}, "pediatric.information_source_observers_and_reliability": {"dataAbsentReason": "asked-unknown"}}, "expected": {"expected_data_absent_reasons": {"pediatric.birth_weight_length_and_head_circumference": "asked-unknown", "pediatric.information_source_observers_and_reliability": "asked-unknown"}, "expected_safety_level": "routine", "expected_stop_reason": "required_targets_addressed_with_absent_data", "expected_max_turns": 90, "forbidden_assertions": ["diagnosis.language_delay", "diagnosis.autism"]}, "provenance": provenance(SOURCES)}
    proxy = routine("learning_school"); proxy["pediatric.information_source_observers_and_reliability"] = {"value": "보호자와 담임교사 메모를 바탕으로 원격 답변"}
    out["PED-SCHOOL-PROXY-REMOTE.json"] = {"id": "PED-SCHOOL-PROXY-REMOTE", "simulation_language": "ko", "persona": {"age": 8}, "encounter_context": {"care_setting": "primary_care", "encounter_type": "new_encounter", "interview_initiator": "caregiver", "interview_mode": "video", "available_information": ["referral_letter"], "time_constraint": "scheduled", "clinical_responsibility": "referral_support"}, "initial_statement": {"ko": "학교 학습 문제를 보호자가 교사 의견과 함께 답합니다."}, "hidden_state": proxy, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_max_turns": 90, "forbidden_assertions": ["diagnosis.intellectual_disability", "diagnosis.adhd"]}, "provenance": provenance(SOURCES)}
    extra = routine("established_condition_followup"); extra["pediatric.caregiver_goal_priority_and_other_detail"] = {"value": "질문과 별개로 치료 시간표 변경도 요청하고 싶음"}
    out["PED-UNRELATED-ADDITIONAL-COMMENT.json"] = {"id": "PED-UNRELATED-ADDITIONAL-COMMENT", "simulation_language": "ko", "persona": {"age": 5}, "initial_statement": {"ko": "발달 치료 추적과 다른 의견이 있습니다."}, "hidden_state": extra, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_max_turns": 90, "forbidden_assertions": ["diagnosis.treatment_failure"]}, "provenance": provenance(SOURCES)}
    multi = routine("motor_coordination"); multi["pediatric.caregiver_goal_priority_and_other_detail"] = {"value": "운동 발달 외에 반복되는 귀 통증도 별도 평가받고 싶음"}
    out["PED-MULTI-RFE-EAR-PAIN.json"] = {"id": "PED-MULTI-RFE-EAR-PAIN", "simulation_language": "ko", "persona": {"age": 4}, "initial_statement": {"ko": "운동이 서툴고 귀도 자주 아파요."}, "hidden_state": multi, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_max_turns": 90, "forbidden_assertions": ["diagnosis.motor_delay", "diagnosis.otitis_media"]}, "provenance": provenance(SOURCES)}
    return out


def main():
    f = fragment(); graph, rules = base_graph_and_rules(prefix=P, rfe=RFE, display="Paediatric Growth or Development Concern", intents=[("intent.characterize_symptom", "Characterize Growth and Developmental Concern"), ("intent.screen_red_flags", "Screen Regression Neurologic Feeding Illness and Safeguarding Risk"), ("intent.differentiate_common_causes", "Assess Growth Feeding Sensory Medical and Social Context"), ("intent.risk_assessment", "Assess Function Screening Intervention and Family Goals")]); primary, research = source_docs()
    concepts = [("248290002", "Developmental delay (disorder)"), ("54840006", "Failure to thrive (disorder)"), ("36440009", "Failure to gain weight (finding)"), ("19410003", "Macrocephaly (disorder)")]
    mapping = {"id": M, "version": VERSION, "status": "research_only", "review_status": "unreviewed", "terminology": {"system": SN, "version": "http://snomed.info/sct/900000000000207008/version/20260701", "source": "STOM"}, "focus_concepts": [{"code": c, "display": d, "concept_active": True, "attribute_count_returned": 0} for c, d in concepts], "verified_attribute_ids": ["246112005", "363714003", "363698007"], "validation": {"method": "build_time_live_fhir_lookup_and_mrcm_summary", "checked_at": ACQUIRED_AT, "raw_response_cached": False, "complete_mrcm_snapshot": False, "clinical_rule_authority": False, "result": "provisional_pass"}, "screening_semantics": {"diagnosis_inferred": False, "age_norm_interpreted_by_runtime": False, "licensed_tool_reproduced": False, "raw_measurements_preserved": True}, "provenance": provenance(["source.stom.pediatric-growth.20260716"])}
    docs = [("knowledge/base/primary-care-pediatric-growth-development.json", graph), ("rules/base/primary-care-pediatric-growth-development.json", rules), ("knowledge/generated/pediatrics/growth-development/pediatric-growth-development.json", f), ("mappings/terminology/snomed-mrcm-pediatric-growth-development.json", mapping), ("sources/manifests/primary-care-pediatric-growth-development.json", primary), ("sources/manifests/primary-care-pediatric-growth-development-research.json", research), ("policies/primary-care-pediatric-growth-development-completion.json", completion(f))]
    for path, doc in docs: write_json(path, doc)
    for name, case in cases(f).items(): write_json("simulation/patients/pediatrics/growth-development/" + name, case)


if __name__ == "__main__": main()
