#!/usr/bin/env python3
"""Materialize unreviewed epistaxis pre-visit knowledge."""
from profile_support import *

P, RFE = "epistaxis", "rfe.epistaxis"
M, SN = "mapping.snomed-mrcm.epistaxis", "http://snomed.info/sct"
ACQUIRED_AT = "2026-07-16T01:00:00Z"
SOURCES = ["source.aao-hnsf.epistaxis.2020", "source.nhs.epistaxis.2023", "source.rch.epistaxis.2026", "source.stom.epistaxis.20260716"]
G = {k: f"group.epistaxis.{k}" for k in ("routing", "safety", "episode", "local", "bleeding", "followup")}
C, S, D, R = ["intent.characterize_symptom"], ["intent.screen_red_flags"], ["intent.differentiate_common_causes"], ["intent.risk_assessment"]


def Q(fid, display, value_type, key, wording, score, groups, intents, **kwargs):
    return entry(P, fid, display, value_type, key, wording, score, key, groups, intents=intents, **kwargs)


def fragment():
    e = [
        Q("epistaxis.primary_group", "Primary Epistaxis Presentation", "coded", "primary-group", "이번 방문은 지금 계속되는 코피, 멈춘 한 번의 코피, 반복되는 코피, 외상·시술 후 코피, 항응고제·출혈질환 관련 상담, 이전 치료 후 추적 중 무엇에 가깝나요?", 190, [G["routing"]], C, allowed_values=["active_current_bleeding", "single_resolved_episode", "recurrent_episodes", "post_trauma_or_procedure", "antithrombotic_or_bleeding_risk", "post_treatment_followup", "other_unclear"]),
        Q("epistaxis.airway_difficulty_or_cannot_handle_blood", "Airway or Blood Handling Compromise", "boolean", "airway", "지금 숨쉬기 어렵거나 목 뒤로 많은 피가 넘어가 뱉어내지 못하나요?", 189, [G["safety"]], S, safety_relevant=True),
        Q("epistaxis.heavy_active_after_correct_continuous_pressure", "Persistent Heavy Bleeding", "boolean", "persistent-heavy", "앞으로 숙여 코의 말랑한 부분을 10~15분 연속 눌렀는데도 많은 피가 계속 나오나요?", 188, [G["safety"], G["episode"]], S, safety_relevant=True),
        Q("epistaxis.weak_faint_confused_or_shock_features", "Haemodynamic Warning", "boolean", "shock", "코피와 함께 쓰러질 듯함·실신, 심한 어지럼·쇠약, 창백함·식은땀 또는 의식 혼란이 있나요?", 187, [G["safety"]], S, safety_relevant=True),
        Q("epistaxis.major_head_or_facial_trauma", "Major Trauma Warning", "boolean", "major-trauma", "교통사고·높은 곳 낙상·강한 얼굴 충격 뒤 코피가 났거나 코 변형·맑은 물 같은 분비물이 있나요?", 186, [G["safety"], G["local"]], S, safety_relevant=True),
        Q("epistaxis.large_swallowed_blood_repeated_vomiting", "Large Swallowed Blood or Vomiting", "boolean", "swallowed-vomit", "많은 피를 삼켜 반복해서 피를 토하거나 구토가 계속되나요?", 185, [G["safety"]], S, safety_relevant=True),
        Q("epistaxis.anticoagulant_with_uncontrolled_or_recurrent_bleeding", "Anticoagulant Bleeding Warning", "boolean", "anticoagulant", "항응고제·항혈소판제를 복용 중이며 코피가 멈추지 않거나 짧은 시간 안에 반복되나요?", 184, [G["safety"], G["bleeding"]], S, safety_relevant=True),
        Q("epistaxis.multisite_bleeding_or_extensive_petechiae", "Systemic Bleeding Warning", "boolean", "multisite", "코피와 함께 잇몸·소변·대변 등 다른 부위 출혈이나 갑자기 많은 멍·점상출혈이 있나요?", 183, [G["safety"], G["bleeding"]], S, safety_relevant=True),
        Q("epistaxis.child_under_two_unexplained", "Epistaxis under Two Years", "boolean", "under-two", "만 2세 미만 아이에게 뚜렷한 가벼운 외상 없이 코피가 났나요?", 182, [G["safety"], G["local"]], S, safety_relevant=True),
        Q("epistaxis.suspected_button_battery_or_hazardous_foreign_body", "Hazardous Nasal Foreign Body", "boolean", "foreign-body", "코 안에 단추형 건전지·자석·화학물질 또는 위험한 이물이 들어갔을 가능성이 있나요?", 181, [G["safety"], G["local"]], S, safety_relevant=True),
        Q("epistaxis.packing_complication_fever_pain_or_rebleeding", "Nasal Packing Complication", "boolean", "packing-complication", "현재 코 패킹·지혈재가 있으며 심한 재출혈, 호흡곤란, 고열·심해지는 통증 또는 패킹 이탈이 있나요?", 180, [G["safety"], G["followup"]], S, safety_relevant=True),

        Q("epistaxis.information_source_and_reliability", "Information Source", "string", "information-source", "내용은 본인 관찰, 보호자·목격자 설명, 사진·영상 또는 의료기록 중 무엇에 근거하나요?", 169, [G["episode"]], C),
        Q("epistaxis.current_bleeding_status_and_last_seen", "Current Bleeding Status", "string", "current-status", "지금 피가 나는지, 완전히 멈췄는지, 마지막으로 확인한 시각을 알려주세요.", 168, [G["episode"]], C, terminology_binding={"system": SN, "code": "249366005"}, mrcm_ref=M),
        Q("epistaxis.onset_date_time_and_activity", "Episode Onset", "string", "onset", "이번 코피가 시작된 날짜·시각과 당시 자고 있었는지, 운동·목욕·코를 만지거나 풀었는지 알려주세요.", 167, [G["episode"]], C),
        Q("epistaxis.duration_timed_and_longest_episode", "Episode Duration", "string", "duration", "이번 출혈과 가장 길었던 출혈이 각각 몇 분이었나요? 시계로 잰 것인지 추정인지 알려주세요.", 166, [G["episode"]], C),
        Q("epistaxis.first_aid_method_pressure_site_and_duration", "First Aid Technique", "string", "first-aid", "앉아 앞으로 숙이고 코의 말랑한 부분을 놓지 않고 눌렀나요? 누른 시간과 중간에 확인했는지 알려주세요.", 165, [G["episode"]], C),
        Q("epistaxis.response_to_pressure_and_other_measures", "Response to First Aid", "string", "response", "압박 전후 출혈이 멈춤·감소·변화 없음 중 어떻게 달라졌고 다른 조치를 했나요?", 164, [G["episode"]], C),
        Q("epistaxis.estimated_amount_and_estimation_method", "Estimated Bleeding Amount", "string", "amount", "피의 양을 휴지·거즈 수, 용기, 옷이나 침구 젖음 등 관찰 가능한 방식으로 알려주세요.", 163, [G["episode"]], C),
        Q("epistaxis.laterality_and_apparent_source", "Laterality and Apparent Source", "string", "laterality", "왼쪽·오른쪽·양쪽 중 어디에서 시작했고 늘 같은 쪽인지 알려주세요.", 162, [G["episode"], G["local"]], C),
        Q("epistaxis.posterior_flow_clots_and_swallowed_blood", "Posterior Flow and Clots", "string", "posterior-flow", "목 뒤로 피가 넘어감, 큰 혈전, 삼킨 피와 메스꺼움·구토 여부를 알려주세요.", 161, [G["episode"]], C),
        Q("epistaxis.episode_frequency_and_time_pattern", "Episode Frequency", "string", "frequency", "처음인지, 최근 일주일·한 달·1년 동안 몇 번인지와 시간대·계절 등 반복 양상을 알려주세요.", 160, [G["episode"]], R, terminology_binding={"system": SN, "code": "12441001"}, mrcm_ref=M),
        Q("epistaxis.prior_severe_episode_ed_admission_or_transfusion", "Prior Severe Epistaxis", "string", "prior-severe", "이전 코피로 응급실 방문·입원·수혈을 받았거나 빈혈 진단을 받은 적이 있나요?", 159, [G["episode"], G["followup"]], R),

        Q("epistaxis.nose_picking_rubbing_blowing_and_minor_trauma", "Minor Nasal Trauma", "string", "minor-trauma", "코 파기·비비기·세게 풀기, 재채기 또는 가벼운 충격과 출혈의 관계를 알려주세요.", 150, [G["local"]], D),
        Q("epistaxis.nasal_dryness_crusting_and_environment", "Nasal Dryness", "string", "dryness", "코 안 건조·갈라짐·딱지와 난방·냉방·건조한 공기 노출을 알려주세요.", 149, [G["local"]], D),
        Q("epistaxis.rhinitis_uri_congestion_and_sneezing", "Rhinitis or Infection Context", "string", "rhinitis", "코막힘·콧물·재채기·가려움, 감기·발열 또는 알레르기 증상이 있나요?", 148, [G["local"]], D),
        Q("epistaxis.unilateral_obstruction_foul_discharge_or_smell_change", "Unilateral Nasal Warning Features", "string", "unilateral-local", "한쪽 코막힘, 악취 나는 분비물, 냄새 변화 또는 한쪽에 보이거나 만져지는 것이 있나요?", 147, [G["local"]], R),
        Q("epistaxis.nasal_foreign_body_or_intranasal_substance", "Nasal Foreign Body or Substance", "string", "foreign-substance", "코 안 이물 가능성, 비강 약물·스프레이·산소관 또는 코로 흡입한 물질 사용을 알려주세요.", 146, [G["local"]], D),
        Q("epistaxis.recent_nasal_dental_facial_procedure_or_surgery", "Recent Procedure or Surgery", "string", "procedure", "최근 코·부비동·치과·얼굴 시술·수술, 소작·패킹과 날짜 및 이후 출혈을 알려주세요.", 145, [G["local"], G["followup"]], R),
        Q("epistaxis.nasal_pain_tenderness_deformity_and_breathing", "Local Pain and Nasal Function", "string", "local-function", "코 통증·압통·부기·변형과 코로 숨쉬기 어려움이 있는지 알려주세요.", 144, [G["local"]], C),

        Q("epistaxis.anticoagulant_antiplatelet_name_dose_last_use", "Antithrombotic Medicines", "string", "antithrombotic", "항응고제·항혈소판제의 이름·용량·복용 횟수·마지막 복용 시각과 최근 변경을 알려주세요.", 140, [G["bleeding"]], R),
        Q("epistaxis.nsaid_nasal_steroid_otc_herbal_and_supplements", "Other Medicines and Products", "string", "other-medicines", "진통소염제, 비강 스테로이드, 일반약·한약·보충제의 이름과 사용 방법을 알려주세요.", 139, [G["bleeding"], G["local"]], R),
        Q("epistaxis.known_bleeding_platelet_liver_kidney_or_blood_disorder", "Bleeding-related Conditions", "string", "bleeding-conditions", "혈우병·폰빌레브란트병·혈소판 감소, 간·신장·혈액질환 등 출혈 관련 진단을 알려주세요.", 138, [G["bleeding"]], R, terminology_binding={"system": SN, "code": "64779008"}, mrcm_ref=M),
        Q("epistaxis.easy_bruising_gum_bleeding_and_other_sites", "Other Bleeding Symptoms", "string", "other-bleeding", "쉽게 드는 멍, 잇몸 출혈, 혈뇨·혈변 또는 해당되면 과다월경이 있나요?", 137, [G["bleeding"]], R),
        Q("epistaxis.prolonged_bleeding_after_cuts_dental_or_surgery", "Bleeding after Challenges", "string", "challenge-bleeding", "작은 상처, 발치·치과치료, 수술·출산 뒤 예상보다 오래 출혈한 적이 있나요?", 136, [G["bleeding"]], R),
        Q("epistaxis.family_history_bleeding_or_hht_features", "Family Bleeding and HHT Context", "string", "family", "가족의 반복 코피·출혈질환과 본인·가족의 입술·입안·손가락 붉은 혈관점 또는 폐·뇌 혈관기형을 알려주세요.", 135, [G["bleeding"]], R, terminology_binding={"system": SN, "code": "21877004"}, mrcm_ref=M),
        Q("epistaxis.blood_pressure_hypertension_and_measurement_context", "Blood Pressure Context", "string", "blood-pressure", "고혈압 진단과 최근 혈압 수치·측정 시각·측정 상황을 알려주세요. 혈압만으로 코피 원인을 단정하지 않습니다.", 134, [G["bleeding"]], R),
        Q("epistaxis.anemia_symptoms_and_recent_cbc", "Anaemia Context", "string", "anemia", "창백함·피로·두근거림·숨참과 최근 혈색소·혈소판 등 혈액검사 결과가 있나요?", 133, [G["bleeding"]], R),
        Q("epistaxis.pregnancy_postpartum_context", "Pregnancy or Postpartum Context", "string", "pregnancy", "해당되면 임신 주수 또는 산후 시기와 다른 출혈·혈압 문제를 알려주세요.", 132, [G["bleeding"]], R),

        Q("epistaxis.previous_examination_endoscopy_tests_and_results", "Previous Assessment", "string", "previous-assessment", "이전 코 진찰·내시경, 혈액검사·영상검사의 날짜와 주요 결과를 알려주세요.", 125, [G["followup"]], R),
        Q("epistaxis.previous_treatment_cautery_packing_and_response", "Previous Treatment Response", "string", "previous-treatment", "보습·연고·스프레이, 소작·패킹·수술 등 이전 치료와 효과·부작용·재발 시점을 알려주세요.", 124, [G["followup"]], R),
        Q("epistaxis.current_packing_type_date_and_followup_plan", "Current Packing and Follow-up", "string", "packing", "현재 패킹·지혈재가 있다면 종류, 넣은 날짜, 제거·재진 계획과 받은 주의사항을 알려주세요.", 123, [G["followup"]], R),
        Q("epistaxis.smoking_vaping_occupation_and_irritant_exposure", "Exposure Context", "string", "exposure", "흡연·전자담배와 분진·화학물질·건조 공기 등 직업·환경 노출을 알려주세요.", 122, [G["followup"]], R),
        Q("epistaxis.sleep_work_school_and_activity_impact", "Functional Impact", "string", "function", "코피 때문에 수면·학교·업무·운동·외출 또는 불안이 얼마나 달라졌나요?", 121, [G["followup"]], R),
        Q("epistaxis.patient_priority_and_other_detail", "Patient Priority and Other Detail", "string", "other-detail", "질문에 없지만 의료진에게 꼭 전달할 내용, 가장 걱정되는 점과 원하는 도움을 알려주세요.", 80, [G["routing"], G["followup"]], C),
    ]
    safety = [("airway", "epistaxis.airway_difficulty_or_cannot_handle_blood", "emergency"), ("persistent-heavy", "epistaxis.heavy_active_after_correct_continuous_pressure", "emergency"), ("shock", "epistaxis.weak_faint_confused_or_shock_features", "emergency"), ("major-trauma", "epistaxis.major_head_or_facial_trauma", "emergency"), ("swallowed-vomit", "epistaxis.large_swallowed_blood_repeated_vomiting", "emergency"), ("anticoagulant", "epistaxis.anticoagulant_with_uncontrolled_or_recurrent_bleeding", "urgent"), ("multisite", "epistaxis.multisite_bleeding_or_extensive_petechiae", "urgent"), ("under-two", "epistaxis.child_under_two_unexplained", "urgent"), ("foreign-body", "epistaxis.suspected_button_battery_or_hazardous_foreign_body", "emergency"), ("packing-complication", "epistaxis.packing_complication_fever_pain_or_rebleeding", "urgent")]
    rules = [safety_rule(P, key, {"fact": fid, "equals": True}, level, 1000 if level == "emergency" else 990) for key, fid, level in safety]
    return {"id": "knowledge.generated.epistaxis", "version": VERSION, "status": "research_only", "usage_modes": ["research_test", "simulation"], "source_manifest": "source-manifest.primary-care-epistaxis-research", "default_refresh": default_refresh(), "extra_nodes": [{"id": v, "type": "ClinicalGroup", "display": v.split(".")[-1]} for v in G.values()], "group_hypothesis_edges": [], "safety_rules": rules, "entries": e, "provenance": provenance(SOURCES)}


def completion(f):
    p = completion_policy(prefix=P, fragment=f, presentation_fact="epistaxis.primary_group", question_budget=65, source_refs=SOURCES)
    common = ["epistaxis.information_source_and_reliability", "epistaxis.current_bleeding_status_and_last_seen", "epistaxis.onset_date_time_and_activity", "epistaxis.duration_timed_and_longest_episode", "epistaxis.first_aid_method_pressure_site_and_duration", "epistaxis.response_to_pressure_and_other_measures", "epistaxis.estimated_amount_and_estimation_method", "epistaxis.laterality_and_apparent_source", "epistaxis.posterior_flow_clots_and_swallowed_blood", "epistaxis.episode_frequency_and_time_pattern", "epistaxis.nose_picking_rubbing_blowing_and_minor_trauma", "epistaxis.nasal_dryness_crusting_and_environment", "epistaxis.rhinitis_uri_congestion_and_sneezing", "epistaxis.unilateral_obstruction_foul_discharge_or_smell_change", "epistaxis.nasal_foreign_body_or_intranasal_substance", "epistaxis.recent_nasal_dental_facial_procedure_or_surgery", "epistaxis.nasal_pain_tenderness_deformity_and_breathing", "epistaxis.anticoagulant_antiplatelet_name_dose_last_use", "epistaxis.nsaid_nasal_steroid_otc_herbal_and_supplements", "epistaxis.known_bleeding_platelet_liver_kidney_or_blood_disorder", "epistaxis.easy_bruising_gum_bleeding_and_other_sites", "epistaxis.prolonged_bleeding_after_cuts_dental_or_surgery", "epistaxis.family_history_bleeding_or_hht_features", "epistaxis.blood_pressure_hypertension_and_measurement_context", "epistaxis.anemia_symptoms_and_recent_cbc", "epistaxis.previous_treatment_cautery_packing_and_response", "epistaxis.sleep_work_school_and_activity_impact", "epistaxis.patient_priority_and_other_detail"]
    cases = {"active_current_bleeding": ["epistaxis.prior_severe_episode_ed_admission_or_transfusion", "epistaxis.previous_examination_endoscopy_tests_and_results"], "single_resolved_episode": ["epistaxis.prior_severe_episode_ed_admission_or_transfusion"], "recurrent_episodes": ["epistaxis.prior_severe_episode_ed_admission_or_transfusion", "epistaxis.previous_examination_endoscopy_tests_and_results", "epistaxis.pregnancy_postpartum_context", "epistaxis.smoking_vaping_occupation_and_irritant_exposure"], "post_trauma_or_procedure": ["epistaxis.prior_severe_episode_ed_admission_or_transfusion", "epistaxis.previous_examination_endoscopy_tests_and_results", "epistaxis.current_packing_type_date_and_followup_plan"], "antithrombotic_or_bleeding_risk": ["epistaxis.prior_severe_episode_ed_admission_or_transfusion", "epistaxis.previous_examination_endoscopy_tests_and_results", "epistaxis.pregnancy_postpartum_context"], "post_treatment_followup": ["epistaxis.previous_examination_endoscopy_tests_and_results", "epistaxis.current_packing_type_date_and_followup_plan", "epistaxis.smoking_vaping_occupation_and_irritant_exposure"], "other_unclear": ["epistaxis.patient_priority_and_other_detail"]}
    p["required_facts"]["routine"], p["conditional_required_facts"] = common, [{"selector_fact": "epistaxis.primary_group", "cases": cases}]
    return p


def source_docs():
    defs = [
        ("source.aao-hnsf.epistaxis.2020", "AAO-HNSF", "Clinical Practice Guideline: Nosebleed (Epistaxis)", "CPG-2020", "https://www.entnet.org/quality-practice/quality-products/clinical-practice-guidelines/nosebleed-epistaxis/", "clinical_guideline", ["For patients aged 3 years or older, document factors increasing frequency or severity, including personal or family bleeding disorders and anticoagulant or antiplatelet use.", "Recurrent unilateral bleeding or recurrent bleeding despite packing or cautery merits localization assessment; education and follow-up response are part of care."]),
        ("source.nhs.epistaxis.2023", "NHS", "Nosebleed", "reviewed-2023-12-05", "https://www.nhs.uk/conditions/nosebleed/", "public_health_guidance", ["Immediate assessment features include bleeding beyond 10 to 15 minutes, excessive bleeding, large swallowed blood with vomiting, head injury, weakness or dizziness and breathing difficulty.", "First aid is forward posture and continuous pressure above the nostrils for 10 to 15 minutes."]),
        ("source.rch.epistaxis.2026", "Royal Children's Hospital Melbourne", "Clinical Practice Guideline: Epistaxis", "updated-2026-04", "https://www.rch.org.au/clinicalguide/guideline_index/Epistaxis/", "clinical_guideline", ["Paediatric history includes recurrent frequency, easy bruising, gum bleeding, prolonged bleeding after procedural challenges, family bleeding history and medicines.", "Unexplained epistaxis under 2 years, prolonged bleeding despite pressure, bilateral or systemic features and haemodynamic compromise require heightened assessment."]),
        ("source.stom.epistaxis.20260716", "Infoclinic", "STOM epistaxis terminology lookup", "SNOMEDCT-20260701", "https://stom.infoclinic.co", "terminology_server", ["FHIR lookup confirmed active epistaxis disorder, bleeding-from-nose finding, coagulation disorder and hereditary haemorrhagic telangiectasia concepts.", "Terminology and MRCM support representation only and do not determine cause or urgency."]),
    ]
    artifacts = [{"id": i, "kind": "terminology_mrcm_query_summary" if profile == "terminology_server" else "clinical_guidance_metadata", "publisher": pub, "title": title, "version": version, "url": url, "language": "en", "digest": "live_response_summary_not_raw_cache" if profile == "terminology_server" else "metadata_only_not_cached", "license_status": "restricted" if pub in {"AAO-HNSF", "Infoclinic"} else "unknown", "complete": False, "monitor_profile": profile, "last_monitored_at": "2026-07-16", "monitor_result": "current_official_source_confirmed", "assertions": assertions} for i, pub, title, version, url, profile, assertions in defs]
    research = {"id": "source-manifest.primary-care-epistaxis-research", "version": VERSION, "acquired_at": ACQUIRED_AT, "status": "research_only", "artifacts": artifacts, "provenance": provenance([x[0] for x in defs])}
    paths = [("source.repository.foundation", "repository_specification", "FOUNDATION.md", True), ("source.generated.epistaxis", "generated_clinical_knowledge", "knowledge/generated/ent/epistaxis/epistaxis.json", True), ("source.mapping.epistaxis", "terminology_mapping", "mappings/terminology/snomed-mrcm-epistaxis.json", False), ("source.external.epistaxis", "external_source_manifest", "sources/manifests/primary-care-epistaxis-research.json", False), ("source.policy.epistaxis", "runtime_policy", "policies/primary-care-epistaxis-completion.json", True)]
    primary = {"id": "source-manifest.primary-care-epistaxis", "version": VERSION, "acquired_at": ACQUIRED_AT, "artifacts": [{"id": i, "kind": kind, "publisher": "clinical-interview-platform", "version": VERSION, "language": "en", "path": path, "digest": "computed_at_build", "license_status": "allowed" if complete else "unknown", "complete": complete} for i, kind, path, complete in paths], "provenance": provenance(["FOUNDATION.md", "PROJECT_CONTEXT.md"])}
    return primary, research


def cases(f):
    out = {}
    for i, rule in enumerate(f["safety_rules"]):
        fid, level, key = rule["when"]["fact"], rule["then"]["safety_level"], rule["id"].split("safety.")[1]
        out[f"EPISTAXIS-{key.upper()}.json"] = {"id": f"EPISTAXIS-{key.upper()}", "simulation_language": "ko", "persona": {"age": 4 + i * 7}, "initial_statement": {"ko": "코피가 나요."}, "hidden_state": {fid: {"value": True}}, "expected": {"expected_safety_level": level, "expected_safety_action": "human_handoff", "expected_stop_reason": f"{level}_escalation", "expected_triggered_rules_contains": [rule["id"]], "expected_max_turns": 35, "forbidden_assertions": ["diagnosis.posterior_epistaxis", "diagnosis.coagulopathy", "diagnosis.hypertension_caused_epistaxis"]}, "provenance": provenance(SOURCES)}
    policy, by_id = completion(f), {x["fact"]["id"]: x["fact"] for x in f["entries"]}
    def routine(branch):
        required = set(policy["required_facts"]["always"] + policy["required_facts"]["routine"] + policy["conditional_required_facts"][0]["cases"][branch]); values = {}
        for fid in required:
            fact = by_id[fid]; values[fid] = {"value": False if fact["value_type"] == "boolean" else fact.get("allowed_values", ["없음"])[0] if fact["value_type"] == "coded" else "없음"}
        values["epistaxis.primary_group"] = {"value": branch}; return values
    resolved = routine("single_resolved_episode"); resolved["epistaxis.duration_timed_and_longest_episode"] = {"value": "시계로 8분"}; resolved["epistaxis.response_to_pressure_and_other_measures"] = {"value": "올바른 압박 후 완전히 멈춤"}
    out["EPISTAXIS-BOUNDARY-RESOLVED-EIGHT-MINUTES.json"] = {"id": "EPISTAXIS-BOUNDARY-RESOLVED-EIGHT-MINUTES", "simulation_language": "ko", "persona": {"age": 32}, "initial_statement": {"ko": "코피가 났지만 지금은 멈췄어요."}, "hidden_state": resolved, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_max_turns": 70, "forbidden_assertions": ["diagnosis.posterior_epistaxis"]}, "provenance": provenance(SOURCES)}
    absent = routine("recurrent_episodes"); absent.pop("epistaxis.estimated_amount_and_estimation_method"); absent.pop("epistaxis.information_source_and_reliability")
    out["EPISTAXIS-RECURRENT-DATA-ABSENT.json"] = {"id": "EPISTAXIS-RECURRENT-DATA-ABSENT", "simulation_language": "ko", "persona": {"age": 48}, "initial_statement": {"ko": "코피가 반복되는데 양은 잘 모르겠어요."}, "hidden_state": absent, "response_behavior": {"epistaxis.estimated_amount_and_estimation_method": {"dataAbsentReason": "asked-unknown"}, "epistaxis.information_source_and_reliability": {"dataAbsentReason": "asked-unknown"}}, "expected": {"expected_data_absent_reasons": {"epistaxis.estimated_amount_and_estimation_method": "asked-unknown", "epistaxis.information_source_and_reliability": "asked-unknown"}, "expected_safety_level": "routine", "expected_stop_reason": "required_targets_addressed_with_absent_data", "expected_max_turns": 70, "forbidden_assertions": ["diagnosis.coagulopathy"]}, "provenance": provenance(SOURCES)}
    proxy = routine("recurrent_episodes"); proxy["epistaxis.information_source_and_reliability"] = {"value": "보호자가 전화로 답변하며 최근 세 번을 직접 목격함"}
    out["EPISTAXIS-PEDIATRIC-PROXY-REMOTE.json"] = {"id": "EPISTAXIS-PEDIATRIC-PROXY-REMOTE", "simulation_language": "ko", "persona": {"age": 7}, "encounter_context": {"care_setting": "primary_care", "encounter_type": "new_encounter", "interview_initiator": "caregiver", "interview_mode": "telephone", "available_information": ["no_previous_records"], "time_constraint": "scheduled", "clinical_responsibility": "decision_support"}, "initial_statement": {"ko": "아이 코피가 반복되어 보호자가 답합니다."}, "hidden_state": proxy, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_max_turns": 70, "forbidden_assertions": ["diagnosis.child_abuse", "diagnosis.bleeding_disorder"]}, "provenance": provenance(SOURCES)}
    extra = routine("post_treatment_followup"); extra["epistaxis.patient_priority_and_other_detail"] = {"value": "질문과 별개로 예약시간 변경도 요청하고 싶음"}
    out["EPISTAXIS-UNRELATED-ADDITIONAL-COMMENT.json"] = {"id": "EPISTAXIS-UNRELATED-ADDITIONAL-COMMENT", "simulation_language": "ko", "persona": {"age": 55}, "initial_statement": {"ko": "코피 치료 후 점검과 다른 의견이 있어요."}, "hidden_state": extra, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_known_facts": {"epistaxis.patient_priority_and_other_detail": "질문과 별개로 예약시간 변경도 요청하고 싶음"}, "expected_max_turns": 70, "forbidden_assertions": ["diagnosis.nonadherence"]}, "provenance": provenance(SOURCES)}
    multi = routine("recurrent_episodes"); multi["epistaxis.patient_priority_and_other_detail"] = {"value": "반복 코피 외에 최근 피로도 별도 평가받고 싶음"}
    out["EPISTAXIS-MULTI-RFE-FATIGUE.json"] = {"id": "EPISTAXIS-MULTI-RFE-FATIGUE", "simulation_language": "ko", "persona": {"age": 42}, "initial_statement": {"ko": "코피가 반복되고 피곤해요."}, "hidden_state": multi, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_max_turns": 70, "forbidden_assertions": ["diagnosis.anemia"]}, "provenance": provenance(SOURCES)}
    return out


def main():
    f = fragment(); graph, rules = base_graph_and_rules(prefix=P, rfe=RFE, display="Epistaxis or Recurrent Nosebleed", intents=[("intent.characterize_symptom", "Characterize Active and Recurrent Epistaxis"), ("intent.screen_red_flags", "Screen Airway Haemodynamic Trauma and Bleeding Risk"), ("intent.differentiate_common_causes", "Assess Local Trauma Inflammation and Systemic Bleeding Context"), ("intent.risk_assessment", "Assess Treatment Response Recurrence and Functional Impact")]); primary, research = source_docs()
    concepts = [("12441001", "Epistaxis (disorder)"), ("249366005", "Bleeding from nose (finding)"), ("64779008", "Blood coagulation disorder (disorder)"), ("21877004", "Osler hemorrhagic telangiectasia syndrome (disorder)")]
    mapping = {"id": M, "version": VERSION, "status": "research_only", "review_status": "unreviewed", "terminology": {"system": SN, "version": "http://snomed.info/sct/900000000000207008/version/20260701", "source": "STOM"}, "focus_concepts": [{"code": c, "display": d, "concept_active": True, "attribute_count_returned": 0} for c, d in concepts], "verified_attribute_ids": ["246112005", "363714003", "363698007", "272741003"], "validation": {"method": "build_time_live_fhir_lookup_and_mrcm_summary", "checked_at": ACQUIRED_AT, "raw_response_cached": False, "complete_mrcm_snapshot": False, "clinical_rule_authority": False, "result": "provisional_pass"}, "event_semantics": {"diagnosis_inferred": False, "hypertension_causality_inferred": False, "laterality_postcoordination_asserted": False}, "provenance": provenance(["source.stom.epistaxis.20260716"])}
    docs = [("knowledge/base/primary-care-epistaxis.json", graph), ("rules/base/primary-care-epistaxis.json", rules), ("knowledge/generated/ent/epistaxis/epistaxis.json", f), ("mappings/terminology/snomed-mrcm-epistaxis.json", mapping), ("sources/manifests/primary-care-epistaxis.json", primary), ("sources/manifests/primary-care-epistaxis-research.json", research), ("policies/primary-care-epistaxis-completion.json", completion(f))]
    for path, doc in docs: write_json(path, doc)
    for name, case in cases(f).items(): write_json("simulation/patients/ent/epistaxis/" + name, case)


if __name__ == "__main__": main()
