#!/usr/bin/env python3
"""Materialize unreviewed tremor and movement-concern knowledge."""
from profile_support import *

P, RFE = "tremor-movement-concern", "rfe.tremor_movement_concern"
M, SN = "mapping.snomed-mrcm.tremor-movement-concern", "http://snomed.info/sct"
ACQUIRED_AT = "2026-07-16T04:00:00Z"
SOURCES = ["source.nice.ng127.tremor", "source.nice.ng71.parkinson", "source.mds.tremor-consensus.2018", "source.ninds.tremor.2025", "source.stom.tremor.20260716"]
G = {k: f"group.movement.{k}" for k in ("routing", "safety", "phenomenology", "associated", "context", "function", "followup")}
C, S, D, R = ["intent.characterize_symptom"], ["intent.screen_red_flags"], ["intent.differentiate_common_causes"], ["intent.risk_assessment"]


def Q(fid, display, value_type, key, wording, score, groups, intents, **kwargs):
    return entry(P, fid, display, value_type, key, wording, score, key, groups, intents=intents, **kwargs)


def fragment():
    e = [
        Q("movement.primary_group", "Primary Movement Concern", "coded", "primary-group", "이번 방문은 떨림, 느려짐·경직, 반복되는 비틀림·이상 자세, 갑작스러운 움찔거림, 춤추듯 불규칙한 움직임, 틱·억제 가능한 움직임, 이미 진단된 운동질환 추적 중 무엇에 가깝나요?", 210, [G["routing"]], C, allowed_values=["isolated_tremor", "slowness_stiffness_or_parkinsonian_features", "dystonia_or_abnormal_posture", "jerks_chorea_tics_or_other_involuntary_movement", "medicine_substance_or_metabolic_context", "established_movement_disorder_followup", "other_unclear"]),
        Q("movement.sudden_focal_neurologic_deficit", "Sudden Focal Neurologic Deficit", "boolean", "focal-neurologic", "움직임 변화와 함께 갑자기 한쪽 힘 빠짐·감각 저하, 얼굴 처짐, 말이 어눌함 또는 시야 변화가 생겼나요?", 209, [G["safety"]], S, safety_relevant=True),
        Q("movement.sudden_severe_ataxia_or_unable_to_walk", "Sudden Severe Ataxia", "boolean", "acute-ataxia", "갑자기 심하게 비틀거리거나 서거나 걷지 못하게 되었나요?", 208, [G["safety"]], S, safety_relevant=True),
        Q("movement.seizure_reduced_consciousness_or_unresponsiveness", "Seizure or Reduced Consciousness", "boolean", "seizure-consciousness", "지금 경련, 의식 저하, 깨우기 어려움 또는 평소와 달리 반응하지 않는 상태가 있나요?", 207, [G["safety"]], S, safety_relevant=True),
        Q("movement.airway_swallowing_or_breathing_compromise", "Airway or Swallowing Compromise", "boolean", "airway-swallow", "목·턱이 비틀리거나 굳으면서 숨쉬기 어렵거나 침도 삼키지 못하나요?", 206, [G["safety"]], S, safety_relevant=True),
        Q("movement.fever_severe_rigidity_confusion_or_autonomic_instability", "Fever Rigidity and Confusion", "boolean", "rigidity-fever", "최근 약을 시작·증량·중단한 뒤 고열, 심한 전신 경직, 혼란, 땀·맥박·혈압의 큰 변화가 함께 있나요?", 205, [G["safety"], G["context"]], S, safety_relevant=True),
        Q("movement.possible_poisoning_overdose_withdrawal_or_hypoglycemia", "Toxic or Metabolic Emergency", "boolean", "toxic-metabolic", "약·물질 과량, 갑작스러운 술·진정제 중단 또는 저혈당 가능성과 함께 떨림·행동·의식이 급격히 변했나요?", 204, [G["safety"], G["context"]], S, safety_relevant=True),
        Q("movement.rapid_progression_with_confusion_behavior_or_cognitive_change", "Rapid Progression with Mental Change", "boolean", "rapid-mental-change", "며칠~몇 주 사이 움직임이 빠르게 악화하면서 혼란, 성격·행동 또는 기억 변화가 동반되나요?", 203, [G["safety"], G["associated"]], S, safety_relevant=True),
        Q("movement.repeated_falls_injury_or_cannot_remain_safe", "Immediate Injury Risk", "boolean", "injury-risk", "움직임 때문에 반복해서 넘어지거나 다쳤고 지금 혼자 안전을 유지하기 어렵나요?", 202, [G["safety"], G["function"]], S, safety_relevant=True),
        Q("movement.pregnancy_postpartum_neurologic_or_hypertensive_warning", "Pregnancy or Postpartum Neurologic Warning", "boolean", "pregnancy-warning", "임신 중이거나 출산 후 6주 이내이며 심한 두통·시야 변화·경련·한쪽 증상 또는 매우 높은 혈압과 함께 새 떨림·움직임이 있나요?", 201, [G["safety"], G["context"]], S, safety_relevant=True),
        Q("movement.child_acute_regression_or_new_ataxia", "Child Acute Regression", "boolean", "child-regression", "아이에게 갑자기 걷기·말·손 사용 능력 퇴행, 심한 비틀거림 또는 의식·행동 변화가 생겼나요?", 200, [G["safety"]], S, safety_relevant=True),
        Q("movement.sudden_persistent_severe_involuntary_movement", "Sudden Persistent Involuntary Movement", "boolean", "sudden-involuntary", "갑자기 시작된 심한 불수의운동이 계속되어 먹기·걷기·잠자기 또는 일상생활이 불가능한가요?", 199, [G["safety"], G["function"]], S, safety_relevant=True),
        Q("movement.immediate_self_harm_harm_to_others_or_behavioral_danger", "Immediate Behavioural Danger", "boolean", "behavioral-danger", "충동·환각·혼란과 함께 자신이나 다른 사람을 해칠 위험이 있거나 보호자가 안전을 유지할 수 없나요?", 198, [G["safety"], G["associated"]], S, safety_relevant=True),
        Q("movement.information_source_witness_video_and_reliability", "Information Source and Video", "string", "information-source", "누가 답변하고 누가 움직임을 보았나요? 가능하면 촬영 시각·상황이 확인되는 영상 유무와 서로 다른 관찰도 알려주세요.", 188, [G["routing"]], C),
        Q("movement.age_and_dominant_hand", "Age and Dominant Hand", "string", "age-handedness", "만 나이와 주로 사용하는 손을 알려주세요.", 187, [G["routing"]], C),
        Q("movement.main_concern_onset_date_time_and_speed", "Onset and Speed", "string", "onset", "가장 걱정되는 움직임이 무엇이며 처음 시작한 날짜·시각과 갑자기 또는 서서히 시작했는지 알려주세요.", 186, [G["phenomenology"]], C),
        Q("movement.course_progression_frequency_and_episode_duration", "Course and Episodes", "string", "course", "계속되는지 간헐적인지, 한 번에 얼마나 지속되는지, 빈도와 호전·악화·변동 경과를 알려주세요.", 185, [G["phenomenology"]], C),
        Q("movement.body_sites_laterality_and_spread", "Body Site Laterality and Spread", "string", "site-side", "손·팔·다리·머리·턱·얼굴·몸통·목소리 중 어디에 나타나며 왼쪽·오른쪽·양쪽 차이와 퍼진 순서를 알려주세요.", 184, [G["phenomenology"]], C, terminology_binding={"system": SN, "code": "26079004"}, mrcm_ref=M),
        Q("movement.rest_posture_action_intention_and_task_relationship", "Activation Condition", "string", "activation", "완전히 쉬고 있을 때, 팔을 뻗고 있을 때, 물건을 잡거나 목표에 손을 뻗을 때, 특정 작업 중 언제 나타나거나 심해지나요?", 183, [G["phenomenology"]], C),
        Q("movement.rhythm_speed_amplitude_and_regular_or_irregular", "Movement Appearance", "string", "appearance", "움직임의 빠르기·크기·리듬이 규칙적인지 불규칙한지, 시간이 지나며 어떻게 달라지는지 설명해주세요.", 182, [G["phenomenology"]], C),
        Q("movement.distractibility_entrainment_suppressibility_and_premonitory_urge", "Modifiability and Urge", "string", "modifiability", "다른 일에 집중하거나 일정 박자에 맞출 때 달라지는지, 잠시 억제할 수 있는지, 움직이기 전 참기 어려운 느낌이 있는지 알려주세요.", 181, [G["phenomenology"]], D),
        Q("movement.triggers_stress_sleep_fatigue_cold_hunger_and_exercise", "Common Triggers", "string", "triggers", "스트레스, 수면 부족, 피로, 추위, 공복, 운동, 통증·질병 중 악화 요인과 재현 가능성을 알려주세요.", 180, [G["phenomenology"], G["context"]], D),
        Q("movement.relief_rest_support_alcohol_or_sensory_trick", "Relieving Factors", "string", "relief", "휴식·팔 지지·자세 변경·특정 부위 만지기 또는 음주 후 달라지는지와 지속 시간을 알려주세요. 증상 완화를 위해 음주를 권하지는 않습니다.", 179, [G["phenomenology"]], D),
        Q("movement.handwriting_spiral_cup_utensil_button_and_device_examples", "Task Examples", "string", "task-examples", "글씨·그림, 컵 들기, 수저·단추·면도·화장·휴대전화 사용 중 어떤 동작이 어렵고 실제 예시나 변화가 있나요?", 178, [G["phenomenology"], G["function"]], C),
        Q("movement.slowness_stiffness_reduced_arm_swing_or_freezing", "Slowness and Stiffness", "string", "slowness-stiffness", "동작이 느려짐, 몸이 뻣뻣함, 팔 흔들림 감소, 발이 바닥에 붙는 듯 멈춤이 있나요? 시작 시기와 좌우 차이를 알려주세요.", 170, [G["associated"]], D),
        Q("movement.gait_balance_near_falls_and_falls", "Gait and Falls", "string", "gait-falls", "걷기·방향 전환·균형 변화, 거의 넘어질 뻔함과 실제 낙상의 횟수·손상을 알려주세요.", 169, [G["associated"], G["function"]], R),
        Q("movement.abnormal_posture_twisting_cramp_or_task_specific_spasm", "Dystonic Features", "string", "dystonia-features", "목·턱·손발이 비틀리거나 이상 자세로 굳음, 쥐가 남 또는 글씨·악기 같은 특정 동작에서 경련이 있나요?", 168, [G["associated"]], D, terminology_binding={"system": SN, "code": "15802004"}, mrcm_ref=M),
        Q("movement.jerks_dance_like_movements_tics_or_restlessness", "Other Involuntary Movements", "string", "other-movements", "갑작스런 움찔거림, 춤추듯 불규칙한 움직임, 반복 소리·동작, 가만히 있기 힘든 움직임이 있나요?", 167, [G["associated"]], D),
        Q("movement.weakness_numbness_coordination_or_sensory_change", "Other Neurologic Symptoms", "string", "neurologic", "힘 빠짐, 저림·감각 변화, 물건을 자주 떨어뜨림, 정확히 목표에 닿기 어려움이 있나요?", 166, [G["associated"]], D),
        Q("movement.speech_voice_swallowing_drooling_or_breathing_change", "Bulbar and Voice Symptoms", "string", "speech-swallow", "말이 작거나 어눌해짐, 목소리 떨림, 삼킴 곤란·사레, 침 흘림 또는 호흡 변화가 있나요?", 165, [G["associated"]], R),
        Q("movement.smell_constipation_urinary_orthostatic_and_sexual_symptoms", "Autonomic and Smell Symptoms", "string", "nonmotor-autonomic", "후각 저하, 변비, 소변·성기능 변화, 일어설 때 어지럼이나 실신이 있나요?", 164, [G["associated"]], R),
        Q("movement.sleep_rem_behavior_daytime_sleepiness_and_restless_legs", "Sleep Symptoms", "string", "sleep", "잠꼬대하며 몸을 크게 움직임, 낮 졸림, 불면 또는 다리를 움직이고 싶은 불편감이 있나요?", 163, [G["associated"]], R),
        Q("movement.cognition_mood_anxiety_hallucinations_and_impulse_control", "Cognitive and Psychiatric Symptoms", "string", "mental", "기억·집중 변화, 우울·불안, 환각·망상 또는 도박·쇼핑·성행동·과식 같은 충동 변화가 있나요?", 162, [G["associated"]], R),
        Q("movement.pain_cramp_fatigue_weight_fever_or_systemic_symptoms", "Systemic Symptoms", "string", "systemic", "통증·쥐·피로, 체중 변화, 발열·식은땀 또는 전신 질환 증상이 함께 있나요?", 161, [G["associated"]], D),
        Q("movement.current_medicines_doses_schedule_and_adherence", "Current Medicines", "string", "medicines", "처방약·일반약·주사·한약·보충제의 이름, 용량, 복용 시각과 실제 복용 상태를 알려주세요.", 155, [G["context"]], R),
        Q("movement.recent_started_stopped_or_changed_medicines", "Recent Medicine Changes", "string", "medicine-change", "증상 전후 새로 시작·중단·증량·감량한 약과 날짜, 변화 후 증상 반응을 알려주세요.", 154, [G["context"]], R),
        Q("movement.dopamine_blocker_stimulant_lithium_valproate_antidepressant_bronchodilator_or_thyroid_medicine", "Movement-relevant Medicines", "string", "medicine-classes", "항정신병·구토약, 자극제, 리튬·발프로산, 항우울제, 기관지확장제, 갑상선약 또는 파킨슨병 약 사용 여부와 이름을 알려주세요.", 153, [G["context"]], R),
        Q("movement.caffeine_nicotine_energy_drink_and_other_stimulants", "Stimulant Exposure", "string", "stimulants", "커피·차·에너지음료, 니코틴과 기타 각성 물질의 종류·하루 양·최근 변화를 알려주세요.", 152, [G["context"]], R),
        Q("movement.alcohol_amount_pattern_last_use_relief_and_withdrawal", "Alcohol Context", "string", "alcohol", "음주 종류·양·빈도·마지막 음주, 음주 후 떨림 변화와 줄이거나 끊을 때 악화 여부를 알려주세요.", 151, [G["context"]], R),
        Q("movement.recreational_substances_toxins_and_withdrawal", "Substances and Withdrawal", "string", "substances", "기타 물질 사용, 중독 가능 노출 또는 최근 중단·금단 가능성을 알려주세요.", 150, [G["context"]], R),
        Q("movement.fasting_glucose_thyroid_liver_kidney_and_electrolyte_context", "Metabolic Context", "string", "metabolic", "공복·저혈당과의 관계, 갑상선·간·신장·전해질 질환 또는 최근 관련 검사 결과를 날짜와 함께 알려주세요.", 149, [G["context"]], R),
        Q("movement.neurologic_medical_psychiatric_and_surgical_history", "Medical and Neurologic History", "string", "medical-history", "뇌졸중·발작·머리 손상·감염, 신경·정신·내과 질환과 수술·입원력을 알려주세요.", 148, [G["context"]], R),
        Q("movement.family_history_tremor_parkinsonism_dystonia_or_other_movement", "Family History", "string", "family-history", "가족 중 떨림, 파킨슨병·느려짐, 비틀림·틱·기타 불수의운동이 있는 사람과 발병 나이를 알려주세요.", 147, [G["context"]], R),
        Q("movement.occupation_hobbies_repetitive_task_and_functional_demand", "Occupation and Task Demand", "string", "occupation", "직업·학업·취미와 정밀 손동작, 악기, 필기, 기계·고소 작업 등 증상에 영향을 받는 활동을 알려주세요.", 146, [G["context"], G["function"]], R),
        Q("movement.toxin_pesticide_solvent_metal_or_carbon_monoxide_exposure", "Occupational or Environmental Exposure", "string", "toxin-exposure", "농약, 용제, 금속·망간, 일산화탄소 등 직업·환경 노출과 보호구·노출 시기를 알려주세요.", 145, [G["context"]], R),
        Q("movement.pregnancy_postpartum_and_hormonal_context", "Pregnancy and Hormonal Context", "string", "pregnancy-context", "임신 가능성·임신 주수·출산 후 경과 또는 월경·호르몬 변화와 증상의 관계를 알려주세요.", 144, [G["context"]], R),
        Q("movement.prior_examination_diagnosis_and_specialist_assessment", "Prior Clinical Assessment", "string", "prior-assessment", "이전에 진찰받은 기관·진료과·날짜, 들은 진단 또는 미확정 설명을 그대로 알려주세요.", 138, [G["followup"]], R),
        Q("movement.prior_laboratory_imaging_or_neurophysiology_results", "Prior Test Results", "string", "prior-tests", "혈액검사, 뇌 영상, 근전도·신경검사 등 검사명·날짜·주요 결과와 원본 유무를 알려주세요.", 137, [G["followup"]], R),
        Q("movement.prior_treatment_response_adverse_effects_and_wearing_off", "Treatment Response", "string", "treatment-response", "사용한 약·시술·재활·생활조정의 용량·기간·효과·부작용과 약효가 떨어지는 시간대를 알려주세요.", 136, [G["followup"]], R),
        Q("movement.db_surgery_device_and_programming_context", "Device or Procedure Context", "string", "device", "뇌심부자극술·펌프·주사 등 기기·시술이 있다면 종류·시행일·최근 조정과 현재 문제를 알려주세요.", 135, [G["followup"]], R),
        Q("movement.eating_drinking_dressing_hygiene_and_writing_function", "Activities of Daily Living", "string", "daily-function", "식사·물 마시기, 옷 입기·씻기, 글씨 쓰기에서 혼자 가능한 정도와 필요한 도움을 알려주세요.", 128, [G["function"]], R),
        Q("movement.walking_transfer_stairs_and_mobility_aid_function", "Mobility Function", "string", "mobility", "일어나기·이동·걷기·계단과 지팡이·보행기 사용에서 필요한 도움과 최근 변화를 알려주세요.", 127, [G["function"]], R),
        Q("movement.work_school_social_participation_and_embarrassment", "Participation Impact", "string", "participation", "직장·학교·대인관계·외출을 얼마나 제한하며 당황·낙인 우려가 어떤 영향을 주나요?", 126, [G["function"]], R),
        Q("movement.driving_machine_height_heat_and_water_safety", "Driving and Hazard Safety", "string", "hazard-safety", "운전, 기계·칼·불·뜨거운 물, 높은 곳 또는 물가에서 위험하거나 중단한 활동이 있나요?", 125, [G["function"]], R),
        Q("movement.living_arrangement_caregiver_support_and_fall_plan", "Support and Safety Plan", "string", "support", "혼자 사는지, 도움을 줄 사람·연락 방법과 넘어짐·증상 악화 시 안전 계획이 있는지 알려주세요.", 124, [G["function"]], R),
        Q("movement.patient_concern_goal_and_other_detail", "Patient Goal and Additional Detail", "string", "other-detail", "질문에 없지만 의료진에게 꼭 전달할 내용, 가장 걱정하는 원인과 이번 진료에서 원하는 도움을 알려주세요.", 90, [G["routing"], G["followup"]], C),
    ]
    safety = [("focal-neurologic", "movement.sudden_focal_neurologic_deficit", "emergency"), ("acute-ataxia", "movement.sudden_severe_ataxia_or_unable_to_walk", "emergency"), ("seizure-consciousness", "movement.seizure_reduced_consciousness_or_unresponsiveness", "emergency"), ("airway-swallow", "movement.airway_swallowing_or_breathing_compromise", "emergency"), ("rigidity-fever", "movement.fever_severe_rigidity_confusion_or_autonomic_instability", "emergency"), ("toxic-metabolic", "movement.possible_poisoning_overdose_withdrawal_or_hypoglycemia", "emergency"), ("rapid-mental-change", "movement.rapid_progression_with_confusion_behavior_or_cognitive_change", "urgent"), ("injury-risk", "movement.repeated_falls_injury_or_cannot_remain_safe", "urgent"), ("pregnancy-warning", "movement.pregnancy_postpartum_neurologic_or_hypertensive_warning", "emergency"), ("child-regression", "movement.child_acute_regression_or_new_ataxia", "urgent"), ("sudden-involuntary", "movement.sudden_persistent_severe_involuntary_movement", "urgent"), ("behavioral-danger", "movement.immediate_self_harm_harm_to_others_or_behavioral_danger", "emergency")]
    return {"id": "knowledge.generated.tremor-movement-concern", "version": VERSION, "status": "research_only", "usage_modes": ["research_test", "simulation"], "source_manifest": "source-manifest.primary-care-tremor-movement-concern-research", "default_refresh": default_refresh(), "extra_nodes": [{"id": v, "type": "ClinicalGroup", "display": v.split(".")[-1]} for v in G.values()], "group_hypothesis_edges": [], "safety_rules": [safety_rule(P, k, {"fact": f, "equals": True}, l, 1000 if l == "emergency" else 990) for k, f, l in safety], "entries": e, "provenance": provenance(SOURCES)}


def completion(f):
    p = completion_policy(prefix=P, fragment=f, presentation_fact="movement.primary_group", question_budget=80, source_refs=SOURCES)
    common = ["movement.information_source_witness_video_and_reliability", "movement.age_and_dominant_hand", "movement.main_concern_onset_date_time_and_speed", "movement.course_progression_frequency_and_episode_duration", "movement.body_sites_laterality_and_spread", "movement.rest_posture_action_intention_and_task_relationship", "movement.rhythm_speed_amplitude_and_regular_or_irregular", "movement.triggers_stress_sleep_fatigue_cold_hunger_and_exercise", "movement.handwriting_spiral_cup_utensil_button_and_device_examples", "movement.slowness_stiffness_reduced_arm_swing_or_freezing", "movement.gait_balance_near_falls_and_falls", "movement.weakness_numbness_coordination_or_sensory_change", "movement.speech_voice_swallowing_drooling_or_breathing_change", "movement.current_medicines_doses_schedule_and_adherence", "movement.recent_started_stopped_or_changed_medicines", "movement.dopamine_blocker_stimulant_lithium_valproate_antidepressant_bronchodilator_or_thyroid_medicine", "movement.caffeine_nicotine_energy_drink_and_other_stimulants", "movement.alcohol_amount_pattern_last_use_relief_and_withdrawal", "movement.fasting_glucose_thyroid_liver_kidney_and_electrolyte_context", "movement.neurologic_medical_psychiatric_and_surgical_history", "movement.family_history_tremor_parkinsonism_dystonia_or_other_movement", "movement.occupation_hobbies_repetitive_task_and_functional_demand", "movement.prior_examination_diagnosis_and_specialist_assessment", "movement.prior_laboratory_imaging_or_neurophysiology_results", "movement.prior_treatment_response_adverse_effects_and_wearing_off", "movement.eating_drinking_dressing_hygiene_and_writing_function", "movement.walking_transfer_stairs_and_mobility_aid_function", "movement.work_school_social_participation_and_embarrassment", "movement.driving_machine_height_heat_and_water_safety", "movement.living_arrangement_caregiver_support_and_fall_plan", "movement.patient_concern_goal_and_other_detail"]
    cases = {"isolated_tremor": ["movement.distractibility_entrainment_suppressibility_and_premonitory_urge", "movement.relief_rest_support_alcohol_or_sensory_trick"], "slowness_stiffness_or_parkinsonian_features": ["movement.smell_constipation_urinary_orthostatic_and_sexual_symptoms", "movement.sleep_rem_behavior_daytime_sleepiness_and_restless_legs", "movement.cognition_mood_anxiety_hallucinations_and_impulse_control"], "dystonia_or_abnormal_posture": ["movement.abnormal_posture_twisting_cramp_or_task_specific_spasm", "movement.relief_rest_support_alcohol_or_sensory_trick"], "jerks_chorea_tics_or_other_involuntary_movement": ["movement.jerks_dance_like_movements_tics_or_restlessness", "movement.distractibility_entrainment_suppressibility_and_premonitory_urge"], "medicine_substance_or_metabolic_context": ["movement.recreational_substances_toxins_and_withdrawal", "movement.pain_cramp_fatigue_weight_fever_or_systemic_symptoms", "movement.toxin_pesticide_solvent_metal_or_carbon_monoxide_exposure"], "established_movement_disorder_followup": ["movement.smell_constipation_urinary_orthostatic_and_sexual_symptoms", "movement.sleep_rem_behavior_daytime_sleepiness_and_restless_legs", "movement.cognition_mood_anxiety_hallucinations_and_impulse_control", "movement.db_surgery_device_and_programming_context"], "other_unclear": ["movement.abnormal_posture_twisting_cramp_or_task_specific_spasm", "movement.jerks_dance_like_movements_tics_or_restlessness", "movement.pregnancy_postpartum_and_hormonal_context"]}
    p["required_facts"]["routine"], p["conditional_required_facts"] = common, [{"selector_fact": "movement.primary_group", "cases": cases}]
    return p


def source_docs():
    defs = [
        ("source.nice.ng127.tremor", "NICE", "Suspected neurological conditions: tremor in adults", "NG127-current-2026", "https://www.nice.org.uk/guidance/ng127/chapter/Recommendations-for-adults-aged-over-16", "nice_guidance", ["Parkinsonian tremor suspicion is informed by unilateral or asymmetric rest tremor with stiffness, slowness, balance or gait change; suspected Parkinson's disease warrants specialist referral.", "Suspected essential tremor assessment includes regular-medicine review, thyroid function and alcohol-use assessment; troublesome head tremor may merit movement-disorder referral."]),
        ("source.nice.ng71.parkinson", "NICE", "Parkinson's disease in adults", "NG71-current-2026", "https://www.nice.org.uk/guidance/ng71/chapter/Recommendations", "nice_guidance", ["Tremor, stiffness, slowness, balance problems or gait disorders may prompt suspicion, but diagnosis is clinical and specialist-led.", "This interview records supporting symptoms, function and medicine effects and does not diagnose or recommend medication changes."]),
        ("source.mds.tremor-consensus.2018", "International Parkinson and Movement Disorder Society", "Consensus Statement on the Classification of Tremors", "MovDisord-33-1-75", "https://pmc.ncbi.nlm.nih.gov/articles/PMC6530552/", "clinical_guideline", ["Axis 1 description uses historical and examination features including body distribution, activation condition, frequency and associated signs; Axis 2 concerns etiology.", "The package captures patient-reportable Axis 1 features while preserving diagnostic and etiologic uncertainty."]),
        ("source.ninds.tremor.2025", "NINDS", "Tremor", "2025-05", "https://www.ninds.nih.gov/sites/default/files/2025-05/Tremor.pdf", "public_health_guidance", ["Tremor may involve hands, arms, head, voice, torso or legs and may appear at rest or with posture and voluntary movement.", "History includes onset, body distribution, provoking situations, medicines, substances, family history and functional effects."]),
        ("source.stom.tremor.20260716", "Infoclinic", "STOM tremor and movement terminology lookup", "SNOMEDCT-20260701", "https://stom.infoclinic.co", "terminology_server", ["FHIR lookup confirmed active Tremor, Parkinsonism, Dystonia, Chorea and Myoclonus concepts in the 20260701 edition.", "Terminology lookup and MRCM constrain representation only; they do not classify the observed movement or establish a diagnosis."]),
    ]
    artifacts = [{"id": i, "kind": "terminology_mrcm_query_summary" if profile == "terminology_server" else "clinical_guidance_metadata", "publisher": pub, "title": title, "version": version, "url": url, "language": "en", "digest": "live_response_summary_not_raw_cache" if profile == "terminology_server" else "metadata_only_not_cached", "license_status": "restricted" if pub in {"NICE", "International Parkinson and Movement Disorder Society", "Infoclinic"} else "unknown", "complete": False, "monitor_profile": profile, "last_monitored_at": "2026-07-16", "monitor_result": "current_official_source_confirmed", "assertions": assertions} for i, pub, title, version, url, profile, assertions in defs]
    research = {"id": "source-manifest.primary-care-tremor-movement-concern-research", "version": VERSION, "acquired_at": ACQUIRED_AT, "status": "research_only", "artifacts": artifacts, "provenance": provenance([x[0] for x in defs])}
    paths = [("source.repository.foundation", "repository_specification", "FOUNDATION.md", True), ("source.generated.movement", "generated_clinical_knowledge", "knowledge/generated/neurology/tremor-movement-concern/tremor-movement-concern.json", True), ("source.mapping.movement", "terminology_mapping", "mappings/terminology/snomed-mrcm-tremor-movement-concern.json", False), ("source.external.movement", "external_source_manifest", "sources/manifests/primary-care-tremor-movement-concern-research.json", False), ("source.policy.movement", "runtime_policy", "policies/primary-care-tremor-movement-concern-completion.json", True)]
    primary = {"id": "source-manifest.primary-care-tremor-movement-concern", "version": VERSION, "acquired_at": ACQUIRED_AT, "artifacts": [{"id": i, "kind": kind, "publisher": "clinical-interview-platform", "version": VERSION, "language": "en", "path": path, "digest": "computed_at_build", "license_status": "allowed" if complete else "unknown", "complete": complete} for i, kind, path, complete in paths], "provenance": provenance(["FOUNDATION.md", "PROJECT_CONTEXT.md"])}
    return primary, research


def cases(f):
    out = {}
    for i, rule in enumerate(f["safety_rules"]):
        fid, level, key = rule["when"]["fact"], rule["then"]["safety_level"], rule["id"].split("safety.")[1]
        out[f"MOV-{key.upper()}.json"] = {"id": f"MOV-{key.upper()}", "simulation_language": "ko", "persona": {"age": 30 + i}, "initial_statement": {"ko": "새로운 떨림이나 이상 움직임이 있습니다."}, "hidden_state": {fid: {"value": True}}, "expected": {"expected_safety_level": level, "expected_safety_action": "human_handoff", "expected_stop_reason": f"{level}_escalation", "expected_triggered_rules_contains": [rule["id"]], "expected_max_turns": 40, "forbidden_assertions": ["diagnosis.parkinson_disease", "diagnosis.essential_tremor", "diagnosis.functional_movement_disorder"]}, "provenance": provenance(SOURCES)}
    policy, by_id = completion(f), {x["fact"]["id"]: x["fact"] for x in f["entries"]}
    def routine(branch):
        required = set(policy["required_facts"]["always"] + policy["required_facts"]["routine"] + policy["conditional_required_facts"][0]["cases"][branch]); values = {}
        for fid in required:
            fact = by_id[fid]; values[fid] = {"value": False if fact["value_type"] == "boolean" else fact.get("allowed_values", ["없음"])[0] if fact["value_type"] == "coded" else "없음"}
        values["movement.primary_group"] = {"value": branch}; return values
    routine_case = routine("isolated_tremor"); routine_case["movement.body_sites_laterality_and_spread"] = {"value": "양손, 오른쪽이 더 뚜렷함"}; routine_case["movement.rest_posture_action_intention_and_task_relationship"] = {"value": "컵을 들거나 글씨를 쓸 때"}
    out["MOV-ACTION-TREMOR-ROUTINE.json"] = {"id": "MOV-ACTION-TREMOR-ROUTINE", "simulation_language": "ko", "persona": {"age": 48}, "initial_statement": {"ko": "컵을 들 때 손이 떨립니다."}, "hidden_state": routine_case, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_max_turns": 90, "forbidden_assertions": ["diagnosis.essential_tremor", "treatment.beta_blocker"]}, "provenance": provenance(SOURCES)}
    absent = routine("other_unclear"); absent.pop("movement.information_source_witness_video_and_reliability"); absent.pop("movement.prior_laboratory_imaging_or_neurophysiology_results")
    out["MOV-UNCLEAR-DATA-ABSENT.json"] = {"id": "MOV-UNCLEAR-DATA-ABSENT", "simulation_language": "ko", "persona": {"age": 70}, "initial_statement": {"ko": "가끔 이상하게 움직이는데 자세히 모르겠습니다."}, "hidden_state": absent, "response_behavior": {"movement.information_source_witness_video_and_reliability": {"dataAbsentReason": "asked-unknown"}, "movement.prior_laboratory_imaging_or_neurophysiology_results": {"dataAbsentReason": "asked-unknown"}}, "expected": {"expected_data_absent_reasons": {"movement.information_source_witness_video_and_reliability": "asked-unknown", "movement.prior_laboratory_imaging_or_neurophysiology_results": "asked-unknown"}, "expected_safety_level": "routine", "expected_stop_reason": "required_targets_addressed_with_absent_data", "expected_max_turns": 90, "forbidden_assertions": ["diagnosis.parkinsonism"]}, "provenance": provenance(SOURCES)}
    proxy = routine("established_movement_disorder_followup"); proxy["movement.information_source_witness_video_and_reliability"] = {"value": "보호자가 답변하며 집에서 촬영한 날짜 확인 영상이 있음"}
    out["MOV-PROXY-REMOTE-FOLLOWUP.json"] = {"id": "MOV-PROXY-REMOTE-FOLLOWUP", "simulation_language": "ko", "persona": {"age": 76}, "encounter_context": {"care_setting": "specialist_clinic", "encounter_type": "follow_up", "interview_initiator": "caregiver", "interview_mode": "video", "available_information": ["previous_clinical_memory"], "time_constraint": "scheduled", "clinical_responsibility": "follow_up_support"}, "initial_statement": {"ko": "보호자가 운동질환 추적 문진을 대신합니다."}, "hidden_state": proxy, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_max_turns": 90, "forbidden_assertions": ["diagnosis.progression"]}, "provenance": provenance(SOURCES)}
    conflict = routine("medicine_substance_or_metabolic_context"); conflict["movement.current_medicines_doses_schedule_and_adherence"] = {"value": "본인은 약이 없다고 하나 의뢰서에는 구토약 복용 기록이 있음"}; conflict["movement.patient_concern_goal_and_other_detail"] = {"value": "약 목록 상충을 의료진이 확인해 주길 원함"}
    out["MOV-MEDICINE-CONFLICT.json"] = {"id": "MOV-MEDICINE-CONFLICT", "simulation_language": "ko", "persona": {"age": 62}, "initial_statement": {"ko": "약을 먹은 뒤 떨리는 것 같지만 약 목록이 맞는지 모르겠습니다."}, "hidden_state": conflict, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_max_turns": 90, "forbidden_assertions": ["diagnosis.drug_induced_tremor", "medication.stop"]}, "provenance": provenance(SOURCES)}
    multi = routine("slowness_stiffness_or_parkinsonian_features"); multi["movement.patient_concern_goal_and_other_detail"] = {"value": "느려짐 외에 반복되는 코피도 별도로 상담 원함"}
    out["MOV-MULTI-RFE-EPISTAXIS.json"] = {"id": "MOV-MULTI-RFE-EPISTAXIS", "simulation_language": "ko", "persona": {"age": 66}, "initial_statement": {"ko": "움직임이 느려지고 코피도 자주 납니다."}, "hidden_state": multi, "expected": {"expected_safety_level": "routine", "expected_stop_reason": "all_required_targets_resolved", "expected_max_turns": 90, "forbidden_assertions": ["diagnosis.parkinson_disease", "diagnosis.bleeding_disorder"]}, "provenance": provenance(SOURCES)}
    return out


def main():
    f = fragment(); graph, rules = base_graph_and_rules(prefix=P, rfe=RFE, display="Tremor or Movement Concern", intents=[("intent.characterize_symptom", "Characterize Movement Phenomenology and Course"), ("intent.screen_red_flags", "Screen Acute Neurologic Toxic Metabolic and Functional Danger"), ("intent.differentiate_common_causes", "Assess Associated Features Medicine Substance and Medical Context"), ("intent.risk_assessment", "Assess Function Safety Prior Evaluation and Patient Goals")]); primary, research = source_docs()
    concepts = [("26079004", "Tremor (finding)"), ("32798002", "Parkinsonism (disorder)"), ("15802004", "Dystonia (disorder)"), ("271700006", "Chorea (disorder)"), ("17450006", "Myoclonus (finding)")]
    mapping = {"id": M, "version": VERSION, "status": "research_only", "review_status": "unreviewed", "terminology": {"system": SN, "version": "http://snomed.info/sct/900000000000207008/version/20260701", "source": "STOM"}, "focus_concepts": [{"code": c, "display": d, "concept_active": True, "attribute_count_returned": 0} for c, d in concepts], "verified_attribute_ids": ["246112005", "363714003", "363698007"], "validation": {"method": "build_time_live_fhir_lookup_and_mrcm_summary", "checked_at": ACQUIRED_AT, "raw_response_cached": False, "complete_mrcm_snapshot": False, "clinical_rule_authority": False, "result": "provisional_pass"}, "movement_semantics": {"movement_class_inferred": False, "diagnosis_inferred": False, "etiology_inferred": False, "laterality_postcoordinated_without_site_validation": False, "patient_video_interpreted_by_runtime": False}, "provenance": provenance(["source.stom.tremor.20260716"])}
    docs = [("knowledge/base/primary-care-tremor-movement-concern.json", graph), ("rules/base/primary-care-tremor-movement-concern.json", rules), ("knowledge/generated/neurology/tremor-movement-concern/tremor-movement-concern.json", f), ("mappings/terminology/snomed-mrcm-tremor-movement-concern.json", mapping), ("sources/manifests/primary-care-tremor-movement-concern.json", primary), ("sources/manifests/primary-care-tremor-movement-concern-research.json", research), ("policies/primary-care-tremor-movement-concern-completion.json", completion(f))]
    for path, doc in docs: write_json(path, doc)
    for name, case in cases(f).items(): write_json("simulation/patients/neurology/tremor-movement-concern/" + name, case)


if __name__ == "__main__": main()
